- examples/utils.dst
- src/compiler/boot.dst
There seems to be some problem with ast-unwrap(1) and recursion. It seems that subsequent calls and changes the argument of ast-unarwap doesn't work but i have not a clear mind right now. I might test it later.
I added a put-in (it took me more that expected to implement it due to if-let). 
Before you push your implementations of array literals, maybe we could use [] to  avoid (tuple ...) when writing macros? I think it would be very convenient.
> Fix if-let when-let and add put-in (assoc-in)

- tools/cook.janet
To link a module to dynamic libraries I need add -l... options at the end of the link command.
for example :
````
>:~/janet/gsl$ janet build
mkdir -p build
cc -c gsl_janet.c  -std=c99 -Wall -Wextra -fpic -O2 -o build/gsl_janet.o
cc -c build/gsl_lib.janet.c  -std=c99 -Wall -Wextra -fpic -O2 -o build/gsl_lib.janet.o
cc -shared -std=c99 -Wall -Wextra -fpic -O2 -o build/gsl.so build/gsl_janet.o build/gsl_lib.janet.o  -lgsl -lblas
````
````
>:~/janet/gsl$ cat build.janet
(import cook)
(cook/make-native
:name "gsl"
:embedded @["gsl_lib.janet"]
:source @["gsl_janet.c"]
:cflags (string cook/CFLAGS)
:lflags " -lgsl -lblas")
````
This change has to be completed for windows (I know almost nothing about dev on windows ...)
> Added :lflags option to cook/make-native

- README.md
- examples/numarray/build.janet
- examples/numarray/numarray.c
- src/core/io.c
- src/core/parse.c
- src/core/peg.c
- src/core/value.c
- src/core/vm.c
- src/include/janet/janet.h
Allow get and set specials for abstract types. This also allows method invocation for abstract types by implementing method calls the same way tables do.
> Get set abstract

- src/core/vm.c
```
janet:78:> (@"abc" 0)
error: expected string|symbol|keyword|array|tuple|table|struct|buffer, got 0
in _thunk [repl] (tailcall) at (79:88)
```
after the patch :
```
janet:0:> (@"abc" 0)
97
```
> Fix buffer (and string) used as callee for indexing.

- src/core/buffer.c
- src/core/pp.c
- src/core/string.c
- src/core/util.h
- test/suite4.janet
Adding string/format function 
This patch provides string/format function.
A snprintf like function with some specialization for Janet.
%p (for pretty printing Janet values) etc.
This code is mostly copy/paste from lua/lstrlib.c
I wrote this code because I'm really need it.
But I'm not sure it should be included in core janet source.
(a dedicated extern module can do the job of course.)
```
janet:329:> (def o {:k 1 :v [1 2 3]})
{:k 1 :v (1 2 3)}
janet:402:> (print (string/format @"" "pi=%8.5f\nobject : %.2p" math/pi o))
pi= 3.14159
object : {:k 1 :v (...)}
nil
```
> string/format  

- Makefile
Fixes #45 - make install fails on some platforms when calling mandb
> Don't call mandb during install

- src/core/io.c
- src/include/janet.h
Register `core/file` abstract type to allow acccess to janet file object in native C module.
For example in a native module we can do something like :
```C
struct IOFile {
FILE *file;
int flags;
};
FILE * get_janet_iostream(const Janet *argv, int32_t n) {
const JanetAbstractType *iof_at=janet_get_abstract_type(janet_ckeywordv("core/file"));
if (iof_at==NULL)
janet_panic("core/file abstract type  not registered");
struct IOFile * iof =(struct IOFile *)janet_getabstract(argv,n,iof_at);
return iof->file;
}
```
> Register core/file abstract type

- src/core/core.janet
- test/suite5.janet
Handle case when index `i` is nil in `drop-until` function, to fix this error:
```clj
(drop-until pos? @[-1 -2 -3])
error: bad slot #1, expected integer, got nil
in <cfunction>
in drop-until [core.janet] at (21740:21758)
in _thunk [repl] (tailcall) at (1:29)
```
> Fix nil error on drop-until fn

- src/core/marsh.c
The function definition is complete after the last '}', so the ';' is
a separate empty declaration, which is not actually valid in C99.
> Remove spurious ';' after function definitions

- Makefile
- README.md
- src/include/janet.h
Other defaults could be set in the Makefile, like the default installation path, but it would probably mess up the structure. This gets it to build successfully by default on 64-bit Haiku (instructions for 32-bit are included).
> Add support for Haiku

- examples/primes.janet
"Primes" compilation was failing due to `compile error: unknown symbol "string/pretty" at (386:413) while compiling ./examples/primes.janet`. I changed `(print (string/pretty (primes 100)))` to '(pp (primes 100))` and it is working properly now. 
```
@[2   
3   
5   
7   
11  
13  
17  
19  
23  
29  
31  
37  
41  
43  
47  
53  
59  
61  
67  
71  
73  
79  
83  
89  
97] 
```
> Primes example fixed

- src/boot/boot.janet
- src/mainclient/init.janet
This allows syntax checkers like the emacs [flycheck](https://www.flycheck.org/en/latest/) to check the source without side effects. Currently, I am just not executing the REPL when this option is supplied, but I am open to suggestions on what to do there.
> Add a 'compile-only' flag to the command line

- src/boot/boot.janet
In some cases it is useful to examine the available bindings for environments other than the current fiber's. This allows 'all-bindings' and 'all-dynamics' to take an optional argument specifying the environment to search.
For reference, my immediate goal for this is to add completions for janet functions to 'janetsh', which performs completion logic in a fiber that does not have the user's REPL environment as a parent.
> Allow all-bindings and dynamics to search specific env

- src/boot/boot.janet
- src/core/parse.c
- src/mainclient/init.janet
Implements #121
I think this could use some more tests, but I wanted to go ahead and get it up for review. I'm not 100% sure the `memcpy` on 877 is sound, as I'm not exactly sure of the gc rules for Janet. Also not sure about the key names, if you have an suggestions, I'm open.
> Add support for getting more detailed parser state 

- tools/amalg.janet
When compiling Janet with `JANET_REDUCED_OS`, `os/date` will not be available which breaks the tool amalg.janet. One can check file modification time on the filesystem instead.
> Remove amalg.janet dependency on os/date

- src/boot/boot.janet
docstrings for take-while / take-until and drop-while / drop-until seems to be inverted?
> Update several docstrings.

- Makefile
https://en.wikipedia.org/wiki/Tar_(computing)#Tarbomb
http://www.linfo.org/tarbomb.html
The `--transform` option requires GNU tar: BSD tar uses the option `-s` instead, and its value must omit the initial `s`.
If GNU tar is not an acceptable requirement, another way would be to create a temporary `janet-<version>` directory and put the files there before archiving it.
Edit: add link to issue #163
> Defuse tarbomb: wrap tar file contents in directory, fix #163

- README.md
```
janet:0:> (all-symbols)
compile error: unknown symbol "all-symbols" at (1:13) while compiling repl
```
> Correct old name all-symbols to all-bindings in README

- src/core/gc.c
- src/include/janet.h
A finalizer can be attached to scratch allocations efficiently at any point in
it's lifecycle via janet_sfinalizer. Care was taken to keep allocations aligned
with  platform alignment requirements.
A big drawbacks to this approach is the waste of up to 16 bytes per scratch
allocation in the case the scratch memory does not require a finalizer.
> Add an optional finalizer to scratch resources.

- src/core/array.c
The doc string for `array/ensure` didn't cover the required `growth` parameter. I'm not certain that "rate of growth" most clearly communicates the intent - "unit of growth" may be better.
> Add missing documentation for array/ensure's growth parameter

- src/core/inttypes.c
- test/suite6.janet
A user can use (type n) to find the true type, the old behavior did not
seem useful for most uses of the string function.
> Integers convert to plain number strings.

- src/core/corelib.c
Try to clarify documentation and teach users the correct
way to read the 'in' so it is less likely to be confused
with python's usage of the keyword.
> Update documentation for in and get builtins.

- src/core/corelib.c
- src/core/value.c
- src/include/janet.h
The janet_get_permissive function implements the core semantics
of the 'get' function. The original janet_get implements the semantics of
the 'in' function and also the OP_GET opcode. This slight oddity is
to avoid a backwards incompatible change.
> New capi janet_get_permissive

- src/core/array.c
- src/core/string.c
- src/core/tuple.c
This wastes a few bytes, but might save an argument or two in the future if we avoid someone getting burnt by accident.
> Explain the logic behind negative slice indices.

- src/core/inttypes.c
- src/core/io.c
- src/core/math.c
- src/core/parse.c
- src/core/typedarray.c
- src/core/value.c
- src/core/vm.c
- src/include/janet.h
This change to the c api allows abstract types to indicate
to the runtime if a key was absent, or if it meant to return nil.
> Abstract type getters can indicate key absence.

- src/core/util.c
- src/include/janet.h
The hash key still needs to randomly initialized
for the security advantage, but this patch is a
step closer to avoiding hash based DOS.
Further work may including exposing the raw hash
function for use by abstract types who also choose to
implement hash.
> Use siphash for string hashing.

- src/core/io.c
It is easier to use constructs like defer
with complex control flow if it is safe to close
a file twice.
> Make file/close idempotent.

- janet.1
- src/mainclient/line.c
* I deleted Alt-H and Alt-L because Ctrl-F and Ctrl-B serve the same roles.
* Ctrl-W, Alt-D, Alt-F, and Alt-B behave more similarly to the same key bindings on GNU readline.
* Improved documentation of REPL keybindings on man page.
* Home and End keys now work on more terminal environments.
* Removed bindings for `Esc OH` and `Esc OF` because andrewchambers doesn't need those bindings and the bindings don't seem to make much sense for Home and End. `Esc O` is Single Shift Select of G3 Character Set in xterm. https://invisible-island.net/xterm/ctlseqs/ctlseqs.html
> Make REPL key bindings more similar to those on GNU readline.

- src/core/corelib.c
This fixes #279. But I am not sure, how deep this gets (`quick_asm` suffix is scary for me).
> Fix next function arity

- src/mainclient/shell.c
This is the default readline behavior.
> Make ctrl-d behave like delete, but exit on an empty line.

- src/mainclient/shell.c
Another common binding in readline and its clones.
> Make alt-backspace behave like ctrl-w.

- src/core/os.c
- test/suite7.janet
The first two patches are bugfixes, the third patch adds a new function os/mktime that does the inverse of os/date, i.e. assemble a date from a broken-down date struct.
This is very useful because it also normalizes the date, so you can easily add days to :month-day,
roundtrip, and get the new date, without implementing a whole calendar system.
Unfortunately, `timegm` is not POSIX, but all systems we check for JANET_POSIX except for Solaris have it. Currently we just panic on Solaris, but I could also prepare a MIT-compatible fallback function based on musl libc that does the same thing.
Windows support is untested and just googled.
I'll add unit tests if you think this is a useful addition.
> os/date fixes and os/mktime

- src/core/marsh.c
- src/include/janet.h
Little endian systems were mistakenly being detected as big endian, which was breaking number serialization/deserialization.
Big endian systems had a typo in the unmarshalling code, which was creating subtly broken results.
This fixes both, so test suite passes on little and big endian ppc64 systems, and most likely other big endian systems.
> Fix build and tests on big and little endian PowerPC systems

- src/boot/boot.janet
- `-?>`: _last_ -> _second_
- `-?>>`: _Threading macro._ -> _Short circuit threading macro._
> Correct typo and match wording for consistency

- src/boot/boot.janet
- test/suite8.janet
There was the same problem in the `last` implementation, you already fixed in `first`. It adds tests for both cases
> Fix last for empty collection, add tests

- test/fuzzers/fuzz_dostring.c
Cross-referencing: https://github.com/janet-lang/janet/pull/344
Updated the fuzzer to target unmarshalling, which also helps us avoid executing random commands and infinite loops as discussed above. Do you think this will be better and can I in fact hit the unmarshalling code in this way?
> Updated the libfuzzer to target marshalling.

- auxbin/jpm
I think this is closer to the intended behavior, otherwise we may be deleting things outside the build dir by accident.
> Do not recurse into symlinks when cleaning.

- src/core/os.c
Fix (mostly nonsensible) race condition in multi threaded processes using os/execute with os/setenv.
> Fix (mostly nonsensible) race condition in multi threaded processes 

- meson.build
```
The Meson build system
Version: 0.54.0
Source dir: /wrkdirs/usr/ports/lang/janet/work/janet-1.9.0
Build dir: /wrkdirs/usr/ports/lang/janet/work/janet-1.9.0/_build
Build type: native build
meson.build:225:2: ERROR: Expecting rbracket got string.
'test/suite9.janet'
^
For a block that started at 215,13
test_files = [
^
```
> Unbreak Meson build

- README.md
`janetconf.h` doesn't exist in `src/include` anymore, it looks like it's in `conf`.
> update janetconf.h path in README embedding section

- Makefile
- README.md
Add and document a make target for providing help on the available targets.
This might not be so useful for experienced make users, but could be useful for new contributors who aren't so comfortable with make. I first saw this idea in [Pelican](https://github.com/getpelican/pelican), and have since borrowed it for other projects: https://github.com/getpelican/pelican/blob/bf85991ee648665f2abc224b9d3719c27470e696/pelican/tools/templates/Makefile.jinja2#L61
> Add make help target

- snapcraft.yaml
Snapcraft allows the latest version of Janet to be immediately available
to developers on most popular Linux distributions. This patch provides
the snapcraft.yaml file, which provides information about the package,
how to build it and how to install it.
Both janet and jpm are exposed, though the latter requires a store side
alias to be provided, as snap names also control application names, to
avoid clashes between applications.
For this prototype I've selected classic confinement. Application
language packages are usually provided with classic confinement, as that
is most flexible for developers.
Snaps do not support providing manual pages yet, so no entries for those
were created.
Signed-off-by: Zygmunt Krynicki <me@zygoon.pl>
> Add snapcraft packaging

- src/boot/boot.janet
I've been playing with this language and, as you'd expect, making mistakes. This `dbg` macro has helped to debug them. It dumps values like `pp`, but allows multiple values at once and also displays the variable name.
Sometimes dumping a variable solves a bug more quickly than opening up a full-blown debugger.
```
$ make repl
Janet 1.9.1-d6cd69e  Copyright (C) 2017-2020 Calvin Rose
janet:1:> (def x 42)
42
janet:2:> (def y @[1 :abc 'foo-bar])
(1 :abc foo-bar)
janet:3:> (dbg x "Hello, world!" y)
`x` has value 42
Literal has value "Hello, world!"
`y` has value @[1 :abc foo-bar]
(42 "Hello, world!" @[1 :abc foo-bar])
janet:4:> 
```
If the name is too similar to the existing `debug` function, it could also be named `dump` or `dump-values`.
It is inspired by Rust: …
> Add a dbg macro for easy var dumping

- src/core/typedarray.c
- test/suite5.janet
bug where tarray/new failed to fully check the type of it's last
argument.
> Fix issue #408 -- make "next" work for typed arrays, and also fix

- src/boot/boot.c
- src/boot/boot.janet
- src/mainclient/shell.c
A REPL tweak. Ctrl-C currently exits the REPL. This PR:
* Exits if on column 0 outside of an expression, like before.
* Cancels the current form if inside of an expression, but doesn't exit Janet.
This matches the behaviour of other language REPLs a bit more.
This PR is a bit hacky; it uses a thread-local boolean exposed to Janet and C and exposes a dummy version for bootstrapping. _If_ I know this new behaviour is desired, I'll clean up the PR in a follow-up commit to use a single function at the least and abstract away the check in `run-context`.
I just didn't want to spent too much time on this if users prefer the current Ctrl-C behaviour.
> Make Ctrl-C Cancel the Current Form; Only Exit if Column 0 Outside of Form

- src/core/os.c
- src/include/janet.h
Maybe you had a good reason to not do this. I can see that `_fullpath` is not quite the same as `realpath`, because `realpath` only accepts paths that exist but it still seems like it could be useful.
> Implement os/realpath with _fullpath

- jpm
- tools/patch-jpm.janet
As noted in [a comment](https://github.com/janet-lang/janet/issues/419#issuecomment-644536795) after #419 was closed, using `def-` for `install-paths` rather than `defn-` in the `jpm` script means that the values in the struct are evaluated regardless of whether `install-paths` is ever used. This can cause the script to break if executed within certain directory structures (such as the directory that the release tarball is extracted to). This is not a theoretical problem. It breaks [the GitHub Action workflow](https://github.com/pyrmont/markable/blob/master/.github/workflows/build.yml) I use as part of continuous integration in my Janet projects.
This PR uses `defn-` rather than `def-` to avoid this problem. It updates the calls to `install-paths` to be calls to `(install-paths)`. This …
> Make install-paths a function

- src/core/os.c
I noticed that my PowerPC build of janet returned "unknown" as the os/arch.
This PR detects PowerPC via `defined(__ppc__)`, which I verified via the following C program:
```c
int main() {
#if defined(__ppc__)
return 1;
#else
return 2;
#endif
}
```
(compiled with the stock gcc 4.0.1 which ships with OS X Tiger / Xcode 2.5)
> Add ppc to os/arch

- src/core/pp.c
When `nil` is passed to functions that need to represent the value as a string, Janet uses the value `"nil"` as opposed to the empty string `""`. I am not sure if this was an intentional design decision; I have found it frustrating because it prevents idioms that construct strings using forms like `when`. Clojure, a language similar in many respects to Janet, represents `nil` as the empty string `""` and inspired this patch.
This PR changes the value returned by `janet_to_string_b` for `JANET_NIL` to `""`. It also updates `janet_description_b` to return the value `"nil`" for situations where it makes sense to output a textual representation (e.g. `(pp nil)`).
The existing test suite passes without any modification but I think it would be a good idea to add some tests. Is there a …
> Change default string representation of nil to empty string

- .gitattributes
Much more readable, IMO!.
This is a short-term solution; a better one will be to make Janet an officially-recognized language by sending a PR to https://github.com/github/linguist .
Fixes #433
> Add .gitattributes: syntax highlight .janet files as Clojure

- src/conf/janetconf.h
- src/core/net.c
This PR adds a `JANET_NO_CLOEXEC` define to janetconf.h for systems which don't have `O_CLOEXEC`.
This PR is part of an effort to support janet on OS X Tiger / PowerPC.
> Support for systems missing O_CLOEXEC

- src/conf/janetconf.h
- src/core/os.c
~~This PR adds a trivial implementation of `arc4random_buf()` (based on https://stackoverflow.com/a/12956868/558735) for systems which have `arc4random()` but not `arc4random_buf()`.  This includes PowerPC Macs which are stuck on OS X Tiger.~~
~~This is enabled by uncommenting the `JANET_NO_ARC4RANDOM_BUF` define in `janetconf.h`.~~
This PR modifies `os_cryptorand()` to use `/dev/urandom` on Macs prior to OS X 10.7.
context: https://github.com/janet-lang/janet/issues/430
> Add support for systems which are missing arc4random_buf

- src/boot/table_test.c
- src/core/table.c
I noticed that `janet_table_remove` was returning the key instead of the removed value.
It would be good to have a test for it to avoid regressions, but I have no idea where I should put such a test in the test suit or create a new test suit, so where do I put tests for it?
> Fix janet_table_remove returning the key instead of the value

- README.md
- src/core/features.h
The NetBSD C library's headers do not expose extensions when compiling with `-std=c99` (as opposed to `-std=gnu99` or no 'std' option), so define `_NETBSD_SOURCE` to get `timegm`, and functions that would otherwise require an `_XOPEN_SOURCE` definition, e.g. `realpath`.
Note that, as with FreeBSD, you need `gmake` to compile janet on NetBSD, and can also install it from packages.
I was previously passing `_NETBSD_SOURCE` through NetBSD's packaging system for the janet package, but this stopped working without patches when `BOOT_CFLAGS` was added. Might as well get it compiling from a fresh git clone now...
[Some more random information about _XOPEN_SOURCE as it applies on Solaris-like systems](https://gist.github.com/jperkin/b08f9108daf8d0ac695067d71f882a9d)
> Fix build on NetBSD.

- src/include/janet.h
This PR makes sure JANET_NO_NANBOX is defined for ARM targets and fix #290
> Make sure JANET_NO_NANBOX is defined for ARM targets

- src/core/io.c
It may be misleading to some user to believe it is taking a path to a
file, when it is executing an arbitrary shell command for the first argument.
> Fix function doc to match that of C POPEN

- src/boot/boot.janet
Without this change, net/server -> ev/go errors with:
```
error: bad slot #0, expected fiber, got <function 0x7FF41E2B7190>
in ev/go
in net/server [boot.janet] (tailcall) on line 2742, column 7
in _thunk [./neiloffice] on line -1, column -1
in cli-main [boot.janet] on line 2891, column 37
```
I tried both `ev/go` with `coro` and this solution, which seems to be better. Please let me know which solution you would prefer.
> Fix net server fiber

- src/boot/boot.janet
Based on the discussions in #507, this is an initial implementation of a docstring formatter that can handle Markdown-formatted docstrings. Docstrings are rewrapped dynamically depending on the indentation and column width specified.
It supports:
1. unordered lists (i.e. lists beginning with `* `, `- ` or `+ `);
2. ordered lists (i.e. lists beginning with a number followed by a `. -`);
3. nesting of lists;
4. multi-paragraph list items; and
5. fenced and unfenced code blocks (these are not wrapped).
An example of the docstring proposed by @uvtc in #507 is included. The output of this in the REPL is below:
> Add formatter for Markdown-formatted docstrings

- src/core/features.h
There is a small typo in src/core/features.h.
Should read `source` rather than `soucre`.
> docs: fix simple typo, soucre -> source

- src/boot/boot.janet
This function only takes one argument anyway, and errors if you try to pass more.
> doc for identity

- src/boot/boot.janet
I found the docstring for `keep` a little unclear. This docstring tries to be clearer (and explain the difference with `filter`).
> Clarify description of keep

- src/core/parse.c
- test/suite0006.janet
Following discussion, this PR adds two optional arguments, `line` and `column`, to `(parser/where p)`. It is intended to be used primarily by REPLs.
If a user includes `line` or `line column`, then the parser's state is updated to the specified line (and, if given, column). A basic check is done to ensure that the user cannot set the line to be less than 1 or for column to be less than zero. This PR adds tests to the test suite to confirm the basic functionality works as expected.
This fixes #531.
> Update (parser/where) to support optional line and column

- src/boot/boot.janet
The current implementation will have quadratic behaviour for already
sorted arrays because it picks the last element as pivot. In an sorted
array this splits the array repeatedly into the biggest value and all
other values.
The implementation in this commit uses the *median of three* as pivot.
`janet -e "(sort (range 10000))"` to reproduce quadratic behaviour.
> Improve quicksort to avoid worst case performance on sorted input

- src/core/util.c
- src/core/value.c
#538 
The current standard hash is [djb2](http://www.cse.yorku.ca/~oz/hash.html#djb2) (aka Bernstein hash). When used to combine the hash values of array or KV elements it performs poorly when the elements are numbers.
This can be easily demonstrated by created tables with tuples or structs as keys whose elements are numbers:
```sh
time janet -e '(def tbl @{}) (loop [x :in (range 1000) y :in (range 1000)] (put tbl (tuple 0 x 1 y) true))'
40.78s user 0.07s system 99% cpu 40.862 total
time janet -e '(def tbl @{}) (loop [x :in (range 1000) y :in (range 1000)] (put tbl {0 x 1 y} true))'
48.98s user 0.15s system 99% cpu 49.136 total
```
And with the changes of this PR:
```sh
time build/janet -e '(def tbl @{}) (loop [x :in (range 1000) y :in (range 1000)] (put tbl (tuple 0 x 1 y) true))'
5.89s …
```
> Improve hash for arrays and KVs 

- src/boot/boot.janet
This reverts commit 0ea77cabfb30afc15433581f5888171c1f65aafd.
The change was buggy. A `(break)` ended sorting early and left the array mostly unsorted. Without this bug, the code is slower than the pure quicksort. 
See als https://github.com/janet-lang/janet/pull/543
TODO: add test to test suite that tests sorting on longer arrays?
> Revert my buggy hybrid sort

- src/core/string.c
There are some minor typos in the `string/find-all` documentation added in bcba0c027998319d48c6e4b4ee3715eddf8946e1. This fixes them.
> Fix typos in string/find-all documentation

- src/boot/boot.janet
- src/core/thread.c
I am not sure, why doubling the \n in .c is needed, but without it `(doc thread/new)` prints:
```
repl:1:> (doc thread/new)
cfunction
(thread/new func &opt capacity flags)
Start a new thread that will start immediately. If capacity is
provided, that is how many messages can be stored in the thread's
mailbox before blocking senders. The capacity must be between 1 and
65535 inclusive, and defaults to 10. Can optionally provide flags to
the new thread - supported flags are: 	:h - Start a heavyweight
thread. This loads the core environment by default, so may use more
memory initially. Messages may compress better, though. 	:a - Allow
sending over registered abstract types to the new thread 	:c - Send
over cfunction information to the new thread. Returns a handle to the
new thread.
```
I also …
> Update doc for thread/new and remove ws in loop's

- src/core/ev.c
`ev/choice` is actually called `ev/select`
> Minor typo in ev/rselect docstring

- src/boot/boot.janet
Add support for a profile.janet, along with a flag for disabling it's use in the presence of a JANET_PROFILE env var.
> Add support for a profile.janet

- src/boot/boot.janet
Due to split docstring, `(doc ev/call)` showed only "run the function.".
I also removed some dead whitespace.
> Fix ev/call doc

- src/boot/boot.janet
This adds support for looking up 'module-level' docstrings (discussed in #598) with `(doc)`.
The PR updates `(doc*)` to perform the following:
1. if the subject of `doc` is not a symbol in the environment, search `module/cache`;
2. if no entry exists in the cache for the subject, display the ordinary error message;
3. if an entry does exist in the cache, call `(print-module-entry)` to display the module documentation;
4. if the module does not have a `:doc` dynamic binding at the top-level, display the message `no documentation found` (as would be the case for another binding without documentation).
Because `(doc*)` uses `(module/find)` to get the full path, the documentation functions have been reordered to come after the module loading functions. Unfortunately this shows up as there …
> Display module-level docstrings with (doc)

- src/core/net.c
Fixes an overflow warning from gcc with '-Wstringop-overflow' on
NetBSD-current.
> Replace malloc + memset with calloc.

- src/boot/boot.janet
- test/suite0007.janet
So, tracev can't be used to wrap defs right now, which feels off (but could have valid reasons).
This added the ability to do that, along with a test of it working as expected.
> Change tracev to upscope instead of using let

- README.md
This is a minor change in the README; repeating `doc` twice in order to demonstrate its usage is slightly more confusing than calling `doc` on something that's obviously a different function, like `apply`.
> Use a slightly clearer example of the `doc` fun in README

- src/boot/boot.janet
Makes docstrings easier to read, and reduces confusion with sorted-by and sort-by.
> Switch out `by` to `before?` in sort functions.

- jpm
Hey, this fixes a minor bug I found while using jpm. This errorf call was missing an argument, so if you use a file with an extension other than .c or .cpp when declaring a native module, you see this error message:
```
$ jpm build
not enough values for format
in string/format
in errorf [boot.janet] on line 152, column 10
in declare-native [/Users/alligator/.local/bin/jpm] on line 952, column 9
in _thunk [./project.janet] (tailcall) on line 5, column 1
```
instead of this one:
```
$ jpm build
unknown source file type: badfile.txt, expected .c or .cpp
in errorf [boot.janet] on line 152, column 3
in declare-native [../janet/jpm] on line 983, column 9
in _thunk [./project.janet] (tailcall) on line 5, column 1
```
> Add missing argument to errorf in jpm

- src/boot/boot.janet
Clarify doc for `sort` and `sorted`. Also in `sort`, changed arg name.
> `sort` doc

- src/boot/boot.janet
This PR adds a mechanism to update the source location being used in `run-context`.
The caller of the `run-context` function can provide a function under the `:chunks` parameter. The return value of this function can be used to send a signal to `run-context`. At present, the only return value that can be sent is the keyword `:cancel`.
This PR updates `run-context` to recognise an additional return value, a 2-value tuple `[:source <new-where>]`. The value of `<new-where>` is used to update the source location. If `<new-where>` is not a string, the value originally provided to `run-context` is used instead (or the default `"anonymous"` if no such value was provided).
The `run-context` function evaluates Janet source code:
https://github.com/janet-lang/janet/blob/a5f237993d48b6d4185f17f396cc8 …
> Allow source location in run-context to be updated

- src/boot/boot.janet
The call to `match` added to `run-context` via #642 mistakenly used part of the predicate from the `if` statement it replaced. This PR fixes that error.
> Fix call to match in run-context

- meson.build
Since Meson 0.51, there are special build options for "native:true" builds, prefixed with "build.".  This change breaks cross builds because `janet-boot/src_core_asm.c` is no longer built with `-std=c99`:
```
FAILED: janet-boot.p/src_core_asm.c.o
/usr/bin/gcc -Ijanet-boot.p -I. -I.. -I../src/include -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O3 -pthread -DJANET_BOOTSTRAP -MD -MQ janet-boot.p/src_core_asm.c.o -MF janet-boot.p/src_core_asm.c.o.d -o janet-boot.p/src_core_asm.c.o -c ../src/core/asm.c
../src/core/asm.c: In function 'janet_disasm_bytecode':
../src/core/asm.c:866:5: error: 'for' loop initial declarations are only allowed in C99 mode
for (int32_t i = 0; i < def->bytecode_length; i++) {
^
```
Fixes:
- http://autobuild.buildroot.net/results/355e0992338a8d132050517f83a3884606b …
> meson.build: defaults to c99 for "build.c_std"

- jpm
The `try-real` function in `jpm` didn't pass the path to `os/realpath`. This PR fixes that.
> Fix argument passing to os/realpath in jpm

- meson.build
Don't enforce `-rdynamic` when building statically to avoid the following build failure:
```
/home/giuliobenetti/autobuild/run/instance-2/output-1/host/bin/arm-linux-gcc  -o janet janet.p/meson-generated_.._janet.c.o janet.p/src_mainclient_shell.c.o -Wl,--as-needed -Wl,--allow-shlib-undefined -Wl,-O1 -rdynamic -Wl,-elf2flt -static -Wl,--start-group -lm -ldl -Wl,--end-group -pthread
arm-linux-gcc.br_real: error: unrecognized command line option '-rdynamic'
```
Fixes:
- http://autobuild.buildroot.org/results/a4f927f73a7b80e65408c992d7b6023609a1eacc
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> meson.build: fix static build

- CONTRIBUTING.md
Currently, only project maintainers can add tags to GitHub issues. This PR removes the instruction to add tags in `CONTRIBUTING.md` to avoid confusion.
> Remove instructions to add tags

- meson.build
Fix the following build failure with `-Dsingle_threaded=true` on embedded toolchains without pthread:
```
FAILED: janet.p/meson-generated_.._janet.c.o
/home/buildroot/autobuild/run/instance-3/output-1/host/bin/arm-linux-gcc -Ijanet.p -I. -I.. -I../src/include -fdiagnostics-color=always -pipe -Wall -Winvalid-pch -std=c99 -O3 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Os -pthread -fvisibility=hidden -MD -MQ janet.p/meson-generated_.._janet.c.o -MF janet.p/meson-generated_.._janet.c.o.d -o janet.p/meson-generated_.._janet.c.o -c janet.c
In file included from /home/buildroot/autobuild/run/instance-3/output-1/host/arm-buildroot-linux-uclibcgnueabihf/sysroot/usr/include/stdlib.h:24,
from ../src/include/janet.h:300,
from src/core/features.h:57: …
```
> meson.build: fix build without threads

- Makefile
The current .tar.gz releases dump all of the (13) artifacts into a single output directory. I prefer something that makes the intended destination clear for all of the objects. 
Downsides:
- potentially breaking change if someone has automated deployment from the releases
- removes some Makefile black magic with exhaustive enumeration of the included files
The folder layout I configured, but open to some bike-shedding:
```
bin/
janet
jpm
include/
janet.h
lib/
libjanet.a
libjanet.so
man/man1/
janet.1
jpm.1
src/
janet.c
shell.c
CONTRIBUTING.md
doc.html
LICENSE
README.md
```
> Create Folder Hierarchy for Linux Release

- src/core/specials.c
- test/suite0004.janet
This PR adds support for registering arbitrary metadata to a top-level binding using a struct.
The `handleattr()` function in the `src/core/specials.c` file supports two types of attributes: keywords and strings. Keywords are treated as 'tags' while a string is treated as a docstring. Trying to pass any other Janet type as an attribute results in an error.
This PR updates `handleattr()` to permit a struct to be provided as an attribute. The keys and values of the struct are merged with the binding's environment table. 
Janet supports adding 'attributes' to a top-level binding's environment table as in the following example:
```janet
(defn double :foo "Double the input" [x] (* 2 x))
(dyn 'double) # => @{:doc "(double x)\n\nDouble the input" :foo true :source-map ("repl" 1 1) :value …
```
> Support adding arbitrary metadata to bindings

- jpm
- test/install/project.janet
- test/install/testexec.janet
- test/install/testmod5.cc
Currently jpm's `declare-native` helper handles compilation of C++ source, but only if it has the `.cpp` extension. However, `.cc` is a common extension for C++ source that is not currently supported by jpm, so it felt prudent to implement this support.
This pull request implements support for the `.cc` extension in `declare-native` with a small bit of refactoring to avoid duplicating the code used to handle the `.cpp` file extension. Additionally, a new case has been added to `test/install` with the `.cc` extension to confirm that jpm correctly builds and installs native modules that have `.cc` source file. The existing test cases were executed successfully, so I believe this change does not introduce any regressions to jpm.
> Allow .cc file extension in jpm declare-native

- README.md
As reported in #678, the link is still broken. The problem is that the file in the `/docs` directory is `index.html` not `introduction.html`. This corrects the link.
> Fix link to Introduction

- src/core/os.c
On Apple systems `NSGetEnviron` should be used instead of `extern char **environ`, for better compatibility (e.g. on older systems). See e.g. 
https://epics.anl.gov/tech-talk/2009/msg00536.php
for a discussion of the issue.
This PR makes the change.
> Use _NSGetEnviron() on Apple

- src/core/os.c
- test/suite0009.janet
On windows, nothing was called that would actually terminate a process. I diagnosed this by writing a file-watcher on windows that ran osprey servers.
This should also fix a long-running issue with Janitor
> Add TerminateProcess to janet_proc_gc and os_proc_kill on Windows

- src/core/os.c
Just a quick change to note that `os/time` returns whole seconds while `os/clock` returns with a fractional component that could then be used for timing purposes. I got caught up when I was trying to benchmark a function with `os/time` but was getting integer values of insufficient resolution.
> Note "int" vs "double" representation of seconds in os API

- src/boot/boot.janet
- test/suite0005.janet
This includes the ability to `take` with either a predicate or number on a fiber, and return an array with the taken values.
It doesn't extend the same behaviour to `drop` because, unlike `take`, dropping values on an infinite stream would return another infinite stream, and collecting those into an array would fail.
> Make take/take-while/take-until fiber-aware

- .github/workflows/release.yml
This PR includes a GitHub workflow that will create a draft release when a tag of the form `v*.*.*` is pushed to the GitHub repository. Importantly, it creates builds for Linux and macOS (both on x64 architecture).
You can see the result of a published release on [my fork](https://github.com/pyrmont/janet/releases/tag/v1.17.1). I'll delete that tag in time so for future reference, this is what it looked at the time of this PR:
A few points to note:
1. The tarballs are generated using the command `make build/janet-<tagname>-<platform>-x64.tar.gz` and so archive to a file that includes the platform architecture `x64`. This is different from previous tarballs that were only in the form `janet-<tagname>-<platform>.tar.gz`.
2. Currently, the release is created in draft and needs to be manually …
> Use GitHub Workflow to create release (including building for Linux and macOS)

- src/boot/boot.janet
- src/core/ev.c
I also have found that for `ev/close`, you mention the `(:close stream)` method. It could be good to have it mentioned for some other functions, not only in the `ev` module. If you think so too, I volunteer for the addition.
> Fix typos in ev/go ev/select

- meson.build
- meson_options.txt
- src/conf/janetconf.h
- src/core/ev.c
- src/core/state.h
- src/include/janet.h
~~Note that this is in no way ready for merge. I'm sort of seeking guidance/comments as to this whilst I make it ready for merging.~~
~~This seeks to add kqueue support to Janet for *BSD.~~ ~~I already know there are probably logic errors and at least one case of probably should not compile (latter with regards to NetBSD).~~
~~I'm hoping I can have a little help getting this ready for merging especially as there are parts of the Janet code base where I'm pretty sure I've come to wrong assumptions or simply don't know how it works.~~
~~Welcoming all comments, suggestions, and aid.~~
**EDIT**:
Ready for merge (passes all tests).
This adds kqueue support to Janet for *BSD (see notes below). Would fix #784.
*NOTE*:
~~Might need this tested on other BSD's, otherwise if no one can I may want to …
> Add kqueue support to Janet

- src/core/net.c
This will allow us to set the address we use for outgoing connections.
**All current tests pass**, works as intended as well.
Fixes #787
> Add bind option to net/connect

- src/core/net.c
- test/suite0009.janet
When this is complete we'll have getpeername, getsockname ~~and possibly
getpeerid, getpeerpid,~~ in the net/* API.
~~Definitely will need running through astyle before merge.~~ **DONE**
Borrowed a lot from [wahern/cqueues](https://github.com/wahern/cqueues).
Please comment/suggest others that might be wanted in the net/* API as well as let me know if the code is awful and hint on ways to make it cleaner.
**Note**:
*nix function names are mapped to "nicer" names in this code. I'm not averse to changing the names of stuff if either *nix function names or  something otherwise sensible is preferred.
All functions return a tuple of `(host port)` where port is optional.
Tested as working with AF_INET*, haven't tested with AF_UNIX (should work). All testing done under FreeBSD (will test under …
> Work in progress - more socket functions

- src/core/gc.c
After the UB was fixed in value.c, I tried running the build again and encoutered another instance of UB in gc.c.  With this fixed I'm now able to build janet with ubsan enabled, meaning there's no more UB encountered in janet_boot during the build.
> add NULL check in gc.c to avoid UB

- src/core/ev.c
FreeBSD is the only BSD supporting ABSTIME timers, whereas the rest demand intervals. Janet operates on timestamps,  which are absolute times, as per ABSTIME. The idea was to use that under FreeBSD but not the other BSDs. This commit changes that since ABSTIME breaks when the timeout supplied is for a time prior to whatever the time is now (invalid argument). We now utilize the same logic we use on the other BSDs with FreeBSD to effect interval timeouts since intervals are absolutely sometime beyond now, be it now and less than a millisecond, or more than a millisecond. This will hopefully unbreak BSD builds when running the test suite.
Tested under FreeBSD, NetBSD, and OpenBSD - relying on CI for MacOS.
> Fix #819 timeouts under kqueue on FreeBSD broken

- src/core/ev.c
This fixes #822 
Priorly we only checked exactly one state when an event was received. This was incorrect. A state may have a next state, an action to take after the first in the list of states has been taken. This change acknowledges that and makes the code work with the state list vs just the head of the list.
Tested under FreeBSD, NetBSD, and OpenBSD with success. MacOS is tested by CI and if that flakes we'll need someone to try it on a Mac device.
> Fix #822 - kqueue hang in suite 9.

- src/include/janet.h
I think `janet_rng_double` was meant to be exposed to the C API (since it's not static). Also after I discovered it I wanted to use it 😄 
> P.S. I'm participating in [Hacktoberfest 2021](https://hacktoberfest.digitalocean.com/). If this PR is up to standard and merged, I'd appreciate if the `hacktoberfest-accepted` label could be added. Thanks!
> Expose `janet_rng_double` to the C API

- examples/urlloader.janet
Currently, `examples/urlloader.janet` uses `file/popen`. This PR changes it to use `os/spawn` and corrects some mistakes in the comments.
> Fix URL loader example to use os/spawn

- src/mainclient/shell.c
Previously the repl always exits on SIGINT, this change
means the repl will only exit on SIGINT if the SIGINT handler
causes it to exit.
> Allow C code to block SIGINT.

- src/core/os.c
This at least means users can use something like jsys
or the kill command to signal processes when they want
to send unsupported signals (like SIGTERM).
> Expose process :pid on unix like platforms.

- src/mainclient/shell.c
Raise signals can only be handled by the current thread while
kill signals can be handled by background threads.
> Use kill instead of raise for SIGINT.

- src/core/math.c
- test/suite0011.janet
I am working on the statistical library for Janet, and I found a typo for the gamma function in the `math/`. This PR corrects the typo and adds `log-gamma` function pointing to the correct function.
This PR also adds tests for these two functions and could be the place where we can test the `math` functions.
> Fix math/gamma and add math/log-gamma

- src/boot/boot.janet
The `:current-file` dynamic binding is used by, among other things, `module/expand-path` to resolve relative paths when importing modules using `import`. Currently this means that files which are evaluated via a netrepl server cannot reliably use relative paths because `:current-file` is not updated when the location changes.
This PR causes `:current-file` to be updated to the location of the file being evaluated.
> Update location of current file in run-context

- src/core/io.c
- test/suite0007.janet
Presently, Janet allows a user to send output (via a dynamic binding) to a buffer:
```janet
(def buf @"")
(with-dyns [:out buf]
(print "Hello world"))
(print buf)    #=> "Hello world"
```
This PR updates `cfun_io_print_impl_x` to support sending the output to a 1-argument function:
```janet
(defn prepend [x] (prin "Prepend> " x))
(with-dyns [:out prepend]
(print "Hello world"))    #=> "Prepend> Hello world"
```
Supporting the sending of output to a function would allow a user to stream output over a socket. I am interested in exploring this as part of future improvements to the netrepl server. The idea is that Janet code evaluated in `run-context` could stream its output to a client.
> Support sending output to a function

- examples/async-execute.janet
Without it, an example fails with `No such file or directory`.
> Add search on PATH for async execute example

- examples/numarray/numarray.c
- examples/numarray/test/numarray_tests.janet
In my pursuit for the "number crunching" library for Janet, I started to think about some better presentation/implementation for data in both statistical sets and linear algebra spaces. I found the numarray example in the main repo, to my surprise. 
It used a system-wide import, which I have changed to the absolute one. 
As an exercise, I added the sum function already defined to the numarray object as a method and added length fn and method.
> Improve numarray example

- src/boot/boot.janet
As discussed in #885, the `loop` macro can be confusing in terms of the behaviour of modifiers on nested loops. Indeed, nested loop behaviour isn't expressly explained at all in the docstring.
This PR attempts to clarify behaviour. It also tidies up some minor stylistic issues in the current docstring.
> Clarify nested loop behaviour in loop macro

- src/boot/boot.janet
- src/core/compile.c
This PR introduces a convention for calling `run-context` to prevent the `:current-file` dynamic binding from being incorrectly set.
Revisions were made in 6bf9f894293e224cc99f61f92f22dc134e66f552 and e8c738002bebe7bacd1b1ede3376a98b896f8f6f to update the `:current-file` dynamic binding  if a `:source` argument representing a file path was passed to `run-context`. These changes assumed that `:source` would represent a path unless it was equal to `"<anonymous>"`. This assumption is wrong; indeed a number of functions in `boot.janet` set the value to a description (e.g. `"eval-string"`, `"repl"` etc). The bug was discovered because Janet 1.19.1 breaks the Temple module in the Spork library (which uses `eval-string`).
This PR fixes this problem by adopting a convention that paths are strings …
> Only set :current-file in run-context if source is a path

- src/core/ev.c
- test/suite0009.janet
Fixed a typo in janet_epoll_sync_callback  where `JANET_ASYNC_LISTEN_WRITE` was checked instead of `JANET_ASYNC_LISTEN_READ`.
It caused the runtime to hang when reading from a normal file descriptor, like one from `os/open`.
This PR also introduces a test for `ev/read`, its almost identical to the test for writing to a normal fd.
The only difference is it reads the content back with `:read` instead of `slurp`.
> Fix typo in janet_epoll_sync_callback, add test for "async" read from normal fd

- test/suite0000.janet
This fixes an errant reference to `:redefs` in the test suite (the global binding was renamed to `:redef`).
> Fix 'redefs' typo in test suite

- src/core/ev.c
Fixes #906 on Windows.
Handles returned by `CreateFileA` with `FILE_FLAG_OVERLAPPED` support reading from arbitrary offsets.
The offset is passed to `ReadFile` through the `OVERLAPPED` structure.
Since `state->overlapped` is zeroed in `ev_machine_read`, `ReadFile` would always read from the start of the file and never finish.
This PR changes `ev_machine_read` to update the offset to the number of bytes read before calling `ReadFile`.
> Windows: Fix `ev/read` hanging when called on stream from `os/open`

- src/core/compile.c
I did have this code in an earlier version of PR #898 but it wasn't in the final version (which is my fault). This fixes the problem described by @sogaiu in [this comment](https://github.com/janet-lang/janet/pull/898#issuecomment-1012833139).
> Fix redefinable macros

- src/core/os.c
Same as #431 (Add ppc to os/arch) but for the 64-bit version.
This is tested on a Power9 CPU in Little-Endian mode, on Linux.
> Add ppc64 to os/arch

- src/boot/boot.janet
- src/core/compile.c
- src/core/util.c
- src/core/util.h
- test/suite0009.janet
- test/suite0011.janet
This PR supports looking up missing symbols during the compilation phase of evaluation by calling a function stored under the dynamic binding `:missing-symbol`.
Using the recently added `:redef` dynamic binding, the following workflow is now possible in a REPL-connected editor:[^1]
1. evaluate a buffer that imports a Janet module
2. in a separate buffer, edit the function definition contained in the Janet module
3. evaluate just the function definition
4. use the redefined function in the original buffer without further action
This is really cool and I'm extremely glad it's possible. Of course I'd like to do more. The following is not currently possible:
1. evaluate a buffer that imports a Janet module
2. _add a function definition_ to the Janet module
3. evaluate the function definition …
> Support looking up missing symbols during compilation

- src/core/inttypes.c
- test/suite0006.janet
Currently, there's no way to get the core number back from an `int/` 64-bit integer.
This PR adds a function `(int/to-number)` which converts either an `int/s64` or `int/u64` to a number.
It fails if the input will not fit in a 32-bit int, and uses `janet_wrap_integer` internally.
> add `(int/to-number)`: convert int/s64 and int/u64 to a number

- src/core/inttypes.c
- test/suite0006.janet
Add `int/to-bytes` which writes the bytes of an `int/` type to a buffer. 
Optionally takes a byte order and existing buffer to write to.
> Add int/to-bytes: Serialize int/[su]64 to a buffer

- src/core/value.c
Sorry if this is completely unnecessary, but I found a way to normalize the negative float without branching (https://stackoverflow.com/questions/9657993/how-to-convert-negative-zero-to-positive-zero-in-c/44707354#44707354).
I don't know a good way to profile this sort of change, so feel free to just disregard the PR.
If you have tips on how to benchmark this sort of change, I'd be happy to try it.
> normalize zero without branching

- src/core/os.c
- src/core/util.c
- src/include/janet.h
This PR does two things:
- Change some uses of `__MACH__` to `JANET_APPLE`
- Change `JANET_APPLE` to check for both `__APPLE__` as well as `__MACH__`
Heyo Janet folk,
I came across an implementation of `clock_gettime` for older OS X machines which uses `mach_absolute_time`, but before I get into that...
I had noticed that sometimes `__MACH__` is used and sometimes `JANET_APPLE` is used.  This PR consolidates to using `JANET_APPLE` across the board (I hope that's what was intended by `JANET_APPLE`!).
Also, I realized I didn't actually understand the difference between `__MACH__` vs `__APPLE__`, so I dug a bit and it turns out `__APPLE__` is also defined on System 9, etc, so it looks like the most correct thing is actually to use both.
Apple seems to indicate as much here: …
> Refactor __MACH__ to JANET_APPLE

- src/core/os.c
- src/core/util.c
This PR:
- changes the Mac clock shim to only be used for Macs older than 10.12.
- moves the `AvailabilityMacros.h` include from `os.c` to `util.c`
- removes the unused `mach/clock.h` and `mach/mach.h` includes from `os.c`
In `util.c`, the Mac clock shim was included for all Macs:
```
if defined(JANET_APPLE)
```
However, `clock_gettime()` was added in 10.12, so the clock shim isn't needed from that point forward: 
- https://opensource.apple.com/releases/
- https://opensource.apple.com/source/Libc/Libc-1158.1.2/gen/clock_gettime.c.auto.html
This PR changes the preprocessor logic to only use the clock shim for Macs running OS X older than 10.12:
```
/* clock_gettime() wasn't available on Mac until 10.12. */
#elif defined(JANET_APPLE) && !defined(MAC_OS_X_VERSION_10_12)
```
Update: I also …
> Mac clock shim not needed after 10.12

- meson.build
This causes incorrect version in meson compiles (including homebrew)
In the future you may want to consider using the `version: file` argument.
> Correct version 1.21.1 in meson.build

- Makefile
This PR changes the Makefile to produce dylibs on macOS.
It appears to work:
And it appears that Linux is unaffected:
(heh, I just noticed the SONAME in the makefile needs to be bumped from 1.20 to 1.21)
This is the first time I've needed a conditional inside of a _target_ of a makefile.  I based my solution on the technique presented here https://stackoverflow.com/questions/15977796/if-conditions-in-a-makefile-inside-a-target but if there are better ways, I'm open!
> Produce dylibs on macOS

- src/core/string.c
Add backticks around code values to distinguish them from prose.
Also two typo fixes.
> string.c docstrings

- src/core/table.c
Light editing to `table/raw-get`. Is my change there correct? (t --> the key)
> table.c docstrings

- .github/workflows/release.yml
- .github/workflows/test.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- README.md
There weren't instructions about running `make install` or `make install-jpm-git` and it wasn't obvious why i didn't get a  `jpm` executable until i found the `install-jpm-git` make target. 
I've only tested on macOS but i assume it'll work the same on the other systems I updated it for.
> added make install & install-jpm-git to Readme

- src/core/vm.c
After the last debugging debate, I started using the `trace` function. It works fine, yet it prints to the stdout, which is not ideal when doing webdev.
This commit changes it and traces the function call to stderr, similarly to `tracev`.
> Trace function to the stderr

- test/suite0013.janet
This commit adds a new suite with the `tabseq` tests. For the second one, I thought it would be cool to lint empty `value-body`, but that would require a significant reorganization of the `boot.janet` code. I still think it will be worth doing, so we can start to use this functionality (macro linting) in the core more (yep, a rhyme).
> Add basic test for tabseq

- Makefile
When using make to build an rpm, the current symlink is
created with an absolute path to the buildroot as causes
the make install target to fail with:
```bash
error: Symlink points to BuildRoot: /usr/include/janet.h -> /home/stephen/rpmbuild/BUILDROOT/janet-1.23.0-3.x86_64/usr/include/janet/janet.h
```
We can create the link relatively which makes this more
portable, where:
```bash
ln -sf -t '/home/stephen/rpmbuild/BUILDROOT/janet-1.23.0-3.x86_64/usr/include' janet.h janet/janet.h
```
Resulting in the following symlink:
```bash
ls -la BUILDROOT/usr/include/janet.h
lrwxrwxrwx. 1 stephen stephen 13 Jul  2 08:17 BUILDROOT/usr/include/janet.h -> janet/janet.h
```
This symlink can then be properly packaged without path
issues.
> Use relative path for include/janet.h symlink

- src/boot/boot.janet
docs with inline code blocks used to have any instances of `_` or `*` trigger underline or italic, respectively, which is not how markdown handles this situation.
This pull request fixes this issue so that the content of code blocks is copied literally with no modification.
> stop doc-format detecting other modes within code blocks

- janet.1
This confused me, despite having a fair deal of janet experience.
Also I find the man-page roff format fairly counterintuitive. Maybe consider switching from raw man pages to something like [scdoc](https://git.sr.ht/~sircmpwn/scdoc)? Here is an [example file](https://git.sr.ht/~emersion/hut/tree/master/item/doc/hut.1.scd) and the [format docs](https://man.archlinux.org/man/scdoc.5.en).
> Clarify the documentation of janet -E flag

- src/core/inttypes.c
In C, signed arithmetic overflow is undefined behvior
but unsigned arithmetic overflow is twos complement
Unconditionally switch to unsigned arithmetic internally for +, -, *
This will not affect the result thanks to twos complement awesomeness.
I don't think this will be an issue in these functions,
but it has a history of causing bugs.....
I think this is probably the most important part of #1018 (`NULL + 0` is probably not going to miscompile....)
> Signed integer overflow is undefined behavior in C, avoid it in inttypes.c

- tools/msi/janet.wxs
JPM on windows currently installs its manpage to C:\ directly because this isn't set when installing Janet through the MSI installer
> Set JANET_MANPATH environment variable while installing.

- src/boot/boot.janet
This bit me, so I figured a clearer docstring couldn't hurt.
I also take the chance to make the grammar a bit more consistent with the docs for `sorted` and `sorted-by`
> Explicitly mention that `sort-by` sorts a list in place.

- src/core/os.c
`(os/cpu-count)` is not registered in the core if JANET_REDUCED_OS is enabled, so we can compile it out entirely in that case.
> (os/cpu-count) should not be defined at all with JANET_REDUCED_OS

- src/core/util.c
- src/include/janet.h
`/test/suite0007.janet` failed on cygwin
```
9/11 test/suite0007.janet         FAIL            1.54s   exit status 1
>>> MALLOC_PERTURB_=150 /cygdrive/e/janet/build/janet.exe /cygdrive/e/janet/build/../test/suite0007.janet
―――――――――――――――――――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――――――――――――――――――――
stderr:
Starting suite 7...
error: unable to get sufficient random data
in os/cryptorand [src/core/os.c] on line 1284
in cryptorand-check [/cygdrive/e/janet/build/../test/suite0007.janet] on line 265, column 4294967316
in _thunk [/cygdrive/e/janet/build/../test/suite0007.janet] (tailcall) on line 272, column 4294967305
―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
```
> Use `/dev/urandom` for `janet_cryptorand` on cygwin

- src/core/buffer.c
- src/core/corelib.c
- src/core/ev.c
- src/core/math.c
- src/core/net.c
- src/core/os.c
Only interesting/controversial thing here is that `math/log-gamma`'s usage said `math/lgamma`, which is less a typo and more an overeager macro.
> Fix some docstring typos

- src/boot/boot.janet
- src/core/asm.c
- src/core/bytecode.c
- src/core/compile.c
- src/core/compile.h
- src/core/gc.c
- src/core/marsh.c
- src/core/specials.c
- src/include/janet.h
- test/suite0011.janet
- test/suite0015.janet
I wanted to allow the debugging programmer to evaluate local variables at the point of an error.
To this end I made the symbols available in the JanetFuncDef, and in the debugger I add the local variables to the debugger environment as to let the debugee play around with the values.
I have tried:
* defn
* def in defn
* def in do in defn
* defn in do in defn
* def in defn in defn
* def in do in defn in defn
And similar combinations.
I did not manage to expose variables defined outside a closure, but I imagine the `:environments` of the disassembly might hold the key.
I don't imagine this will be merged as is, but I wanted to give my best shot at this, and let others try it and see what errors might pop up.
My main concern is the structure of the `:slotsyms` data, which is useful but not …
> local symbols available when *debug* is true

- src/core/peg.c
This was an error about the base argument that referenced the tag argument, which might not exist.
Closes #1070.
> fix a segfault in the (number) special

- src/core/features.h
- src/core/os.c
* On DragonFly BSD, we need to define another macro to get access to all sorts of goodies in C99 mode
* Allow `(os/which)` to return `:dragonfly`, which makes the REPL banner look nicer at the very least
```
Janet 1.27.0-01aab666 dragonfly/x64/gcc - '(doc)' for help
repl:1:>
```
> Some basic fixes for DragonFly

- src/core/math.c
I broke this in ab224514f098fe744afff4e4036212e40eea7952.
Before this change:
```
Janet 1.27.0-01aab666 macos/aarch64/clang - '(doc)' for help
repl:1:> (doc math/log-gamma)
cfunction
src/core/math.c on line 292, column 1
(math/"log-gamma" x)
Returns log-gamma(x).
```
After this change:
```
Janet 1.27.0-4e7930fc macos/aarch64/clang - '(doc)' for help
repl:1:> (doc math/log-gamma)
cfunction
src/core/math.c on line 292, column 1
(math/log-gamma x)
Returns log-gamma(x).
```
> remove quotes in math/log-gamma docstring

- src/boot/boot.janet
- test/suite0010.janet
These functions are designed to make it easier to properly preserve the sourcemap and tuple type in macros. This commit also modifies the threading macros to make use of these functions.
---
I've been really enjoying Janet and while working on a DSL I've come across the problem that this pull request attempts to improve. Here is the explanation of the problem and my proposed solution.
Various macros in boot.janet lose the sourcemap information of their arguments due to creating a new modified tuple. This simple program shows an example of this:
```
(-> "String"
(identity)
(+ 1))
```
The error message points to line 1, where the threading macro starts, instead of line 3, where the error actually occurs. When the threading macro is modified to preserve the sourcemaps, the error message is …
> Add `keep-syntax` and `keep-syntax!` functions

- src/core/pp.c
When there is no format to be found after a %, get_fmt_mapping returns NULL.
It then gets called against strlen, which is a typical SEGV.
Check for NULL aginst mapping, which signals a null format being specified.
Note that there are other edge-conditions present.
Namely, consider: `(printf "hello % " "dave")` (format is still null).
Meanwhile, `(printf "hello % s" "dave")` (outputs "hello dave").
> handle null-byte case in scanformat (fixes #1105)

- src/boot/boot.janet
- test/suite0005.janet
This is a functional change, as previously a negative count would be treated the same as 0. But it seems unlikely to cause problems in practice.
This brings a satisfying symmetry to the quadrants of this "table:"
- First element: `(first list)`
- Last element: `(last list)`
- Everything but the first element: `(drop 1 list)`
- Everything but the last element: `(drop -1 list)`
It might make sense to do the same thing for `take`, but because `take` works with fibers, we can't support it completely.
It might be preferable to have a separate `drop-last` function. The negative count thing seems nicer to me, but I don't know if there's precedent for it elsewhere in the standard library.
> drop with a negative count now drops from the end

- src/core/capi.c
- src/include/janet.h
Like getcstring, but operates on a byteview.
When writing bindings (i.e what capi.c is primarily used for), it's common to want to accept a buffer *or* a string rather than just a string.
For this, a byteview is perfect (and why not accept keywords while you're at it?).
However, there's no built-in function for getting a cstring out of a byteview, this adds one.
This also reformulates getcstring to be an edge-case of getcbytes (simply adding an explicit check for stringness).
> Add get/opt cbytes

- src/include/janet.h
Otherwise attempts to use it on some platforms cause the following error `error: initializer element is not a compile-time constant` when attempting to use the corresponding `JANET_REG`.
> Make JANET_FN_S* sourceline const

- src/core/os.c
- test/suite0007.janet
I found that Janet is lacking an efficient way for formatting dates and times. This patch adds a simple `strftime()` wrapper as `os/strftime`. 
Is this something that is acceptable to go into the `os` core lib, or would Spork be a better place?
> Added os.strftime()

- Makefile
This PR adds some smoother support for easy cross compilation.
Building janet requires janet_boot to be run on the host at build time; for this some changes were made
- Added `$(RUN)` variable to allow a emulator to be specified
- Added `.exe` extension to binaries when using MINGW
- `$(UNAME)` can now be overridden from the make cmdline
Examples:
Cross compiling for win32 and running under wine:
```
make  repl  \
CC=x86_64-w64-mingw32-gcc \
LD=x86_64-w64-mingw32-gcc \
UNAME=MINGW \
RUN=wine
Janet 1.27.0-ad7c3bed mingw/x86/gcc - '(doc)' for help
```
Cross compiling for aarch64 and running under qemu:
```
make repl \
CC=aarch64-none-linux-gnu-gcc \
LD=aarch64-none-linux-gnu-gcc \
RUN="qemu-aarch64 -L /tmp/aarch64/"
Janet 1.27.0-ad7c3bed linux/aarch64/gcc - '(doc)' for help
```
> Updated Makefile for better cross-compilation support.

- src/core/features.h
- src/core/net.c
This PR adds the `net/setsockopt` function to `src/core/net.c`; this allows a number of common socket options to be configured to support broadcast and multicast traffic on sockets. Additional options can later be added when needed.
Example for receiving mdns packets:
```
(def sock (net/listen "0.0.0.0" "5353" :datagram))
(net/setsockopt sock :so_broadcast true)
(net/setsockopt sock :ip_add_membership "224.0.0.251")
(net/setsockopt sock :ip_multicast_ttl 255)
(pp (net/read sock 512))
```
What is the appropriate error behavior for:
- Passing wrong options (currently panics)
- the `setsockopt()` call failing (currently panics)
> add net/setsockopt

- Makefile
This makes `make debug` work and `make valtest` show traces with with line numbers. Also valgrind now is run with `--guiet` to hide the banner popping up, resulting in cleaner output.
I saw the `-g` options have been added and removed a few times in the lifetime of the `Makefile`, so I'm not sure what the intention of the authors was with regards to debug symbols.
> Enable debug symbols in janet binary; strip target at 'make install'

- src/boot/boot.janet
- test/suite0010.janet
Relevant issue: #1092
Not sure if all cases are handled here.
> added thaw to complement freeze

- src/core/os.c
- src/core/util.c
- src/core/util.h
- test/suite0007.janet
instead of CLOCK_REALTIME, this matches the description from the documentation of os/clock. Fixes issue #1144
> Add  clock sources to os/clock (:realtime, :monotonic, :cputime)

- src/core/specials.c
- src/core/value.c
This patch improves the error messages for special forms somewhat.
Below is a list with the wrong code, the old error message and the new error message:
```
(defn test [body msg_old msg_new]                                                                                      
(def msg (try (eval body) ([err fib] err)))
(if-not (= msg msg_old) (pp [body msg])))
(def foo @[1 2 3])
(test '(while true)    "expected at least 2 arguments"                                                                             
"expected at least 2 arguments to while")
(test '(var alice)     "expected at least 2 arguments"                                                                           
"expected at least 2 arguments to var") 
(test '(def bob)       "expected at least 2 arguments" …
```
> improved error messages for special forms

- src/core/util.c
Sorry for the flood of PRs.
This one fixes a warning introduced by my own recent `os-clock` change (it did not show up in my local build but I just noticed in CI); it should not affect behavior in any way since the if-else chain is exhaustive and will overwrite the fault initial value of `cid` in any case.
> Fix warning in janet_gettime()

- src/core/corelib.c
- src/core/ev.c
- src/core/inttypes.c
- src/core/peg.c
- src/core/pp.c
```
error: bad slot #1, expected string|symbol|keyword|buffer, got ...
error: bad slot #1, expected a string, symbol, keyword or buffer, got ...
```
```
bad s64 initializer: "donkey"
can not convert string "donkey" to s64
```
In other places error message do not talk about "s64"  but about "64 bit signed integer", would that be preferable here as well?
> Improved various error messages when handling unexpected types.

- src/core/string.c
This adds documentation to string/format, I would appreciate comments on the descriptions.
```
Similar to C's snprintf, but specialized for operating with Janet 
values. Returns a new string.
The following conversion specifiers are supported, where the upper 
case specifiers generate upper case output:
* c: ASCII character.
* d, i: integer, formatted as a decimal number.
* x, X: integer, formatted as a hexadecimal number.
* o: integer, formatted as an octal number.
* f, F: floating point number, formatted as a decimal number.
* e, E: floating point number, formatted in scientific notation.
* g, G: floating point number, formatted in its shortest form.
* a, A: floating point number, formatted as a hexadecimal number.
* s: formatted as a string, precision indicates padding and maximum …
```
> Add docstring to string/format

- src/boot/boot.janet
- test/suite0001.janet
Allows multiple iterable arguments to `mapcat`, `keep`, `count`, `some`, and `all`.
See #1159 for a detailed description of the proposed changes.
> Allow mapcat et al to accept multiple iterable arguments

- src/boot/boot.janet
- test/suite0009.janet
That's what you get for coming up with a nice implementation. Still trying to get this into the stdlib :smile:
> Add file/lines iterator

- Makefile
The problem that #994 was trying to solve (the symlink should be a relative path and not absolute) doesn't actually require the use of the GNU-only `-t`/`-T` option to ln(1).
> More portable method of installing janet.h -> janet/janet.h symlink

- src/core/pp.c
At https://github.com/janet-lang/janet/blob/master/src/core/pp.c#L849, janet_formatbv() pulls a long instead of an int when handling the %d specifier, potentially leading to wrong results:
```C
janet_eprintf(">>> %d\n", (int32_t) - 1);
```
output:
```
>>> 4294967295
```
In the wild this shows like this:
```janet
(buffer/slice @"" 3)                                                  
```
error thrown:
```
error: start index 3 out of range [4294967295,0]
```
The same goes for `%u`  and friends.
> Fix janet_formatbv() type when handling %d %u int specifiers

- src/core/net.c
`net/connect` uses the destination address instead of the binding address for the `bind()` after the `connect()`
> Fixed net/connect binding address

- src/core/ev.c
before doing WSARecvFrom() to prevent crash (likely caused by the memcpy() of `state->from` at line
2301 with the memcpy length set to -1)
> fix for crash on windows in src/core/ev.c: initialze state->fromlen

- src/boot/boot.janet
- test/suite0010.janet
Before adding this, the simplest way to do this was `(not (nil? (index-of val collection)))` or `(truthy? (index-of val collection))`.
In my opinion, this is significantly less clear than the new API `(contains? collection val)`. 
Also adds four new related functions:
- `collection?` - Tests for collection types (intentionally excluding strings)
- `contains-key?` - Checks if a collection contains a key
- For arrays, this checks the index
- `contains-value?` - Checks if a collection contains a value
I would say this use case for `contains?` is pretty important. 
Most major programming languages offer some sort of contains function (Python, Java, Rust).
In Python it's even a keyword (`in`).
Some of the other functions are more debatable.
I intentionally excluded strings for the reasons …
> Add `contains?` helper function to boot.janet

- src/boot/boot.janet
- test/suite-ev.janet
When an error occurs in an `ev/gather` form, it is possible that not all the sibling fibers are canceled.  This can lead to process hangs, if an uncanceled fiber blocks.
The problem is that `each` is not well-defined for tables that are being mutated.  So, sometimes the `(put fibers f nil)` in `cancel-all` causes iteration to skip entries.  It's not deterministic since the hash of a fiber is based on its address.  For integers, it is deterministic, and you can see the effect here:
```janet
(def t @{1 1
2 2
3 3})
(each x t
(put t x nil))
(pp t) # => @{2 2 3 3}
```
A script like this can be used to reproduce the process hangs:
```bash
#!/bin/bash
: ${JANET:=janet}
attempts=100
hangs=0
for i in $(seq $attempts); do
timeout 0.5 "$JANET" -e '
(defn hang [] (ev/take (ev/chan)))
(protect …
```
> Ensure ev/gather fibers are fully canceled on error

- test/helper.janet
- test/suite-array.janet
- test/suite-buffer.janet
- test/suite-corelib.janet
- test/suite-inttypes.janet
- test/suite-io.janet
- test/suite-parse.janet
- test/suite-struct.janet
These tests all hit previously untested code.
Also updated the test `assert` to print line info to make it easier to locate a failed test.
> Added misc tests to increase test coverage

- Makefile
- src/boot/boot.janet
(Not sure if people are willing to pull in this added complexity, but giving it a shot anyway)
This change allows building Janet from the individual source files instead of from the amalgamated `janet.c`; this considerably speeds up parallel builds on modern CPUs;
```
make clean; time make -j NO_AMALG=0 
[...]
real	0m7.882s
```
vs
```
make clean; time make -j NO_AMALG=1 
[...]
real	0m1.481s
```
For me this make the difference between "comfortably and quickly running my tests" and "getting slightly annoyed staring at my screen",
> Added JANET_NO_AMALG flag to Makefile 

- src/core/ev.c
- test/suite-ev.janet
When suspended in `ev/give` or `ev/take`, closing the channel should cause the result of `ev/give` or `ev/take` to be `nil`. 
[ref](https://janet-lang.org/api/ev.html#ev/chan-close)
When suspended in `ev/select`, closing the channel should cause the result of `ev/select` to be `[:close ch]`.
[ref](https://janet-lang.org/api/ev.html#ev/select)
The results were flipped before.
> Fix resumption values when closing a channel

- src/boot/boot.janet
- test/suite-boot.janet
Related issue: #1178 
Allow `take` from the end of bytes or indexed (as `drop` does).
Allow `drop` from fibers (as `take` does).
Return table for `take` from dictionary types.
Allow `drop` from dictionary types (as `take` does).
Increase efficiency for `take` and `drop` with slices.
Check indexed types before bytes.
It isn't clear to me that there is a common use case for taking and dropping from dictionary types. However, the implementation is relatively straight-forward, particularly for take, so I don't know that it should be explicitly forbidden either.
`take` for indexed types isn't slowed any by this change, and `drop` has become significantly faster. `take` has become slightly slower for `bytes` objects due to the type check reordering. I believe that indexed types are a more …
> Make take and drop more symmetric

- src/boot/boot.janet
- test/suite-boot.janet
Related issue: #1186
Simplifies the code generated by the `if-let` macro.
Adds slightly better test coverage.
> Simplify if-let logic

- src/core/compile.c
- test/suite-boot.janet
Previously, `*macro-lints*` was set after the `macroexpand1` fiber was resumed, rather than just before.  And, `*macro-lints*` was never cleared.  This behavior was typically fine since the main users of `compile` pass the same lint array repeatedly, and the first macro expansion (somewhere in boot.janet) never produces a lint.  But, when compiling with a fresh lint array, if the first macro invocation produced a lint, the lint was always lost.
> Fix order in which *macro-lints* is set during expansion

- src/core/peg.c
The use cases involve user-expandable grammars.
For example, consider the IRC nickname specification.
> They SHOULD NOT contain any dot character ('.', 0x2E).
> Servers MAY have additional implementation-specific nickname restrictions.
To implement this, we can do something along these lines:
```janet
(def nickname @{:main '(some :allowed)
:allowed (! (+ :forbidden/dot :forbidden/user))
:forbidden/dot "."
:forbidden/user false})
```
Additionally, it's common in parsing theory to allow matches of the empty string (epsilon). `true` essentially allows for this.
Note that this does not strictly add new functionality, you could emulate this previously using `0` and `(! 0)` respectively, but this should be faster and more intuitive.
The speed improvement primarily comes from `(! 0)` which is …
> peg: add support for "true" and "false" primitives to always/never match

- src/core/os.c
- test/suite-os.janet
Janet raises an error if `os/execute` is called with the same stream being used to redirect both STDOUT and STDERR:
```janet
(def dn1 (os/open "/dev/null" :w))
(def p1 (os/execute ["ls"] :px {:out dn1})) # will not raise an error
(def dn2 (os/open "/dev/null" :w))
(def p2 (os/execute ["ls"] :px {:out dn2 :err dn2})) # will raise an error
```
This problem currently affects JPM when installing with `--silent` (e.g. `jpm --silent install judge`). This PR prevents this error by avoiding the premature closing of file descriptors in `os_execute_impl`.
In 4a40e57cf059011e37aa45d43f48733b8e5546b0, @bakpakin made changes to `os_execute_impl` to address #881. For the purposes of this PR, the relevant lines are:
https://github.com/janet-lang/janet/blob/c3f4dc0c152dd1d08fdd96e406a2847e1a3f9b40/src/cor …
> Avoid prematurely closing file descriptors when redirecting IO

- src/core/parse.c
- src/core/pp.c
Some C escape sequences are not supported in Janet strings, namely:
- `\'`
- `\?`
- `\a`
- `\b`
Full list at https://en.cppreference.com/w/c/language/escape.
Supporting them could be useful to copy-paste strings from other languages (and I need `\b`).
> Add C escape sequences

- Makefile
Janet's Makefile calls `strip` on `make install` to remove certain symbols. This causes macOS to be unable to dynamically load shared objects at runtime. This PR adds the flags `-x` and `-S` which fixes this problem.
As part of #1140,  @zevv added a call to `strip` to remove certain symbols when running `make install`. This does not cause an issue on Linux (and presumably other POSIX systems) but prevents Janet from loading shared object files dynamically on macOS.
A simple example is Janet's [JSON project](https://github.com/janet-lang/json). When the test suite is run on macOS 13.4.1, the output is:
```text
$ jpm -l test
running test/suite0.janet ...
error: could not load native build/json.so: dlopen(build/json.so, 0x0002): symbol not found in flat namespace '_janet_arity'
in native …
```
> Avoid removing too many symbols with strip on macOS

- src/core/inttypes.c
- src/core/vm.c
- test/suite-inttypes.janet
> Add bnot for int types

- src/core/array.c
- src/core/string.c
- src/core/tuple.c
- test/suite-array.janet
Related issue: #1219
The problem with array index -1: Because `array/slice` does not include its end index in the result, it is not possible to slice to the end of the array. Also, because `array/insert` inserts before the given index, it is not possible to insert to the end of the array.
There are two possible solutions to this problem:
1. (Current Solution) Redefine the final index of an array to be -2.
2. (Proposed Solution) Redefine the behavior of `array/slice` and `array/insert` for negative indices.
Notably, the behavior of these two functions is identical for either solution.
I submit for consideration that the proposed solution is more correct and desirable. When indexing from the end of the array, the array should be viewed reversed, as if its end were its front. In other words, …
> `array/remove`: update final array index to be -1

- src/boot/boot.janet
- src/core/corelib.c
- test/suite-boot.janet
- test/suite-corelib.janet
Related issue: #1235
- Moves `range` from `boot.janet` to `corelib.c`
- Adds slightly better test coverage for 3 argument forms
> Move `range` to corelib

- src/boot/boot.janet
These functions may not be overly important, but that doesn't mean that they can't be optimized. The main performance gain here is creating an array with the correct capacity before iteration begins, rather than pushing to an empty array.
```janet
(def xs (range 1000))
(timeit-loop [:timeout 1] "keys  " (keys xs))
(timeit-loop [:timeout 1] "values" (values xs))
(timeit-loop [:timeout 1] "pairs " (pairs xs))
```
master:
```janet
keys   1.000s, 36.86µs/body
values 1.000s, 42.86µs/body
pairs  1.000s, 84.27µs/body
```
branch:
```janet
keys   1.000s, 14.75µs/body
values 1.000s, 19.11µs/body
pairs  1.000s, 56.36µs/body
```
`keys` and `values` are each over twice as fast, and `pairs` is approximately 50% faster.
> Rework `keys`, `values`, `pairs`

- src/boot/boot.janet
Similar to the changes in #1241. The result is approximately twice as fast on any size argument.
```janet
(def a (range 10))
(def b (range 100))
(def c (range 1000))
(timeit-loop [:timeout 1] :a (reverse a))
(timeit-loop [:timeout 1] :b (reverse b))
(timeit-loop [:timeout 1] :c (reverse c))
```
master:
```janet
a 1.000s, 0.4635µs/body
b 1.000s, 3.296µs/body
c 1.000s, 31.49µs/body
```
branch:
```janet
a 1.000s, 0.2932µs/body
b 1.000s, 1.939µs/body
c 1.000s, 17.52µs/body
```
I try not to have more than one open PR at a time, but I thought I might slip these in before the release.
> Rework `reverse`

- src/boot/boot.janet
- src/core/corelib.c
I understand that it's not desirable to move everything to `corelib.c`, especially things that can be implemented simply and concisely in Janet. However, for these three functions I think it may be warranted. Each of these functions compares multiple types, and are used in several places throughout `boot.janet`, and not only in compile-time expanded macros.
For example, in `flatten`:
```janet
(timeit-loop [:timeout 1] :flatten (flatten [[[1 2] 3] 4 [5 [6 7 8] 9]]))
```
master:
```janet
flatten 1.000s, 1.556µs/body
```
branch:
```janet
flatten 1.000s, 0.8098µs/body
```
Nearly half the time taken is spent checking the type.
For the interested, moving these functions increases the size of the executable by 128 bytes, at least on my system:
master:
```janet
$ du -b …
```
> Move `bytes?`, `indexed?`, `dictionary?` to corelib

- src/boot/boot.janet
- Makes `compare-reduce` a macro so that the comparators, which are known at compile time, compile to vm ops rather than function calls.
- Inlines the call to `compare` in the `compare-reduce` macro.
The result is approximately 75% faster for abstract types, and 130% as faster for numbers per invocation.
```janet
(def a (range 10))
(timeit-loop [:repeat 1_000_000] "control " (< ;a))
(timeit-loop [:repeat 1_000_000] "splice  " (compare< ;a))
(timeit-loop [:repeat 1_000_000] "number  " (compare< 0 1))
(timeit-loop [:repeat 1_000_000] "s64 arg0" (compare< (int/s64 0) 1))
(timeit-loop [:repeat 1_000_000] "s64 arg1" (compare< 0 (int/s64 1)))
```
master:
```janet
control  0.213s, 0.2134µs/body
splice   1.792s, 1.792µs/body
number   0.296s, 0.2964µs/body
s64 arg0 0.397s, …
```
> Speed up `compare` functions

- src/boot/boot.janet
Related: #1248
With [feedback](https://github.com/janet-lang/janet/issues/1248#issuecomment-1675925262) from @bakpakin.
before:
```janet
> (reverse [:a :b :c])
@[:c :b :a]
> (reverse "abc")
@[99 98 97]
> (reverse {1 2 3 4 5 6})
@[nil 2 nil]
```
after:
```janet
> (reverse [:a :b :c])
@[:c :b :a]
> (reverse "abc")
@"cba"
> (reverse {1 2 3 4 5 6})
@[6 4 2]
```
> Rework `reverse`, again

- src/core/capi.c
- src/core/wrap.c
- src/include/janet.h
This PR replaces generic `const uint8_t *` and `Janet *` types with the more specific `JanetString`/`JanetSymbol`/`JanetKeyword`/`JanetTuple`/`JanetStruct`/`JanetAbstract`.
This makes it easier for those who are new to the C API (such as myself) to figure out what these functions actually return/take as arguments. I specifically had issues understanding how the `janet_getstring` function worked initially because it appeared to return a pointer to the start of the string without a length.
AFAICT the only reason these functions do not use the more specific types is because their function signatures predate the typedefs existing.
I'll send a PR to update the corresponding docs at https://janet-lang.org if this gets merged.
> Use typedefs for strings, symbols, keywords, tuples, structs, and abstracts.

- src/boot/boot.janet
- Special case common sort usages (`<`, `>`) to use vm ops directly.
- Rewrite `median-of-three` to use 2.667 comparisons on average, rather than 5. It's not as clever, but it is faster.
- Avoid recursing if unnecessary.
The result is approximately 3x faster for these usages, and roughly unchanged for others.
```janet
(use spork/misc)
(def rng (math/rng 12345))
(def a (randomize-array (range 100) rng))
(timeit-loop [:timeout 1]
"sorted "
(sorted a))
(timeit-loop [:timeout 1]
"sort   "
(def b (array/slice a))
(sort b))
(timeit-loop [:timeout 1]
"reverse"
(def b (array/slice a))
(sort b >))
(timeit-loop [:timeout 1]
"compare"
(def b (array/slice a))
(sort b compare<))
```
master:
```janet
sorted  1.000s, 99.43µs/body
sort    1.000s, 100.1µs/body
reverse 1.000s, 98.23µs/body …
```
> Special case common `sort` usages

- src/core/buffer.c
- test/suite-buffer.janet
- test/suite-unknown.janet
Filling a lexical gap, to avoid things like this:
```janet
(buffer (string/from-bytes ;data))
(buffer/push-byte @"" ;data)
```
or [even this](https://github.com/janet-lang/janet/discussions/1253):
```janet
(def buf @"")
(each b data
(buffer/push-byte buf b))
```
Adding this function has increased the size of the executable by 32 bytes on my system:
master:
```
$ du -b `which janet`
801384	/usr/local/bin/janet
```
branch:
```
$ du -b `which janet`
801416	/usr/local/bin/janet
```
Of course, it's also faster than either alternative:
```janet
(var data (range 65 91))
(timeit-loop [:timeout 1]
(buffer/from-bytes ;data))
(timeit-loop [:timeout 1]
(buffer (string/from-bytes ;data)))
(timeit-loop [:timeout 1]
(buffer/push-byte @"" ;data))
```
```janet
buffer/from-bytes 1.000s, …
```
> Add `buffer/from-bytes`

- src/boot/boot.janet
Fixes #1220
Changes `each-template` to update the iteration key after bindings and before the body, rather than after the body. As the iteration key is not exposed to the body, I believe this has no consequence, other than to resolve the linked issue.
```janet
(let [t @{1 true 2 true 3 true 4 true}]
(eachk k t
(when (even? k)
(put t k nil)))
t)
```
master:
```janet
@{1 true 3 true 4 true}
```
branch:
```janet
@{1 true 3 true}
```
> Update `each` keys before body

- src/boot/boot.janet
- test/suite-boot.janet
Updates `any?` and `every?` to be exact functional analogues to `or` and `and`.
- `any?` returns the final value if all preceding values are falsey, rather than `nil`.
- `every?` returns the final value if all preceding values are truthy, rather than `true`.
I believe this makes their definitions more coherent. `any?` would sometimes return an element from the collection (if it were truthy), and sometimes `nil`. `every?` would sometimes return an element from the collection (if it were falsey), and sometimes `true`. After, each will always return an element from the collection.
As their meaning will not have changed when used as a predicate, I believe these changes can be made with minimal fallout. `every?` in particular is much more useful this way. Because of the spatial separation in …
> Update `any?`, `every?`

- src/boot/boot.janet
Creates a helper macro so that the primitive comparators compile to vm ops directly. The boiler plating is approximately the same as would be generated by `each`, except that the key is advanced before the loop to avoid unnecessarily comparing the first value with itself. The result is approximately 4x faster for `min` and `max`, 5x faster for `min-of` and `max-of`, and roughly unchanged for `extreme`.
```janet
(use spork/misc)
(def rng (math/rng 12345))
(def a (randomize-array (range 100) rng))
(timeit-loop [:timeout 1] "min    " (min ;a))
(timeit-loop [:timeout 1] "max    " (max ;a))
(timeit-loop [:timeout 1] "min-of " (min-of a))
(timeit-loop [:timeout 1] "max-of " (max-of a))
(timeit-loop [:timeout 1] "extreme" (extreme < a))
```
master:
```janet
min     1.000s, …
```
> Speed up `min`, `max`

- src/boot/boot.janet
- test/suite-boot.janet
Related: #1275
Makes `:range` more predictable, in particular that:
```janet
(loop [i :range [10]] body)
```
is equivalent to:
```janet
(loop [i :range [0 10] body)
```
rather than producing an infinite loop.
This is consistent with the behavior that the following forms:
```janet
(range 10)
(range 0 10)
```
are also equivalent.
> Allow one-term `:range` and `:down` forms

- src/boot/boot.janet
- src/core/corelib.c
Related: #1279 
- Add `lengthable?`
```
(lengthable? x)
Check if x is a bytes, indexed, or dictionary.
```
- Speed up `keys`, `values`, and `pairs`, while allowing non-lengthable types
- Allow non-lengthable types for `reverse`
- Minor speed improvement for `reverse!`
- Updates some docstrings missed in previous PRs
> Add `lengthable?`

- src/boot/boot.janet
- test/suite-boot.janet
- Speed up `partition`
- Allow `partition` to work with non-lengthable types
- Allow `mean` to work with non-lengthable types
```janet
(def a (range 1000))
(timeit-loop [:timeout 1] "partition" (partition 5 a))
(pp (partition 3 (range 11)))
```
master:
```janet
partition 1.000s, 14.15µs/body
@[(0 1 2) (3 4 5) (6 7 8) (9 10)]
```
branch:
```janet
partition 1.000s, 12.38µs/body
@[(0 1 2) (3 4 5) (6 7 8) (9 10)]
```
---
I spent some time trying to optimize partition specially for dictionary types, but was unable to find anything more efficient than slicing over `values`.
`mean` wouldn't necessarily need to be special-cased for `lengthable?`, as the generic case is only about 10% slower, but it can be done simply.
> Update `partition`, `mean`

- src/boot/boot.janet
- test/suite-boot.janet
Related: #1286
- Adds `:unless` loop modifier
```janet
> (seq [i :range [0 10] :unless (odd? i)] i)
@[0 2 4 6 8]
```
> Add `:unless` loop modifier

- src/boot/boot.janet
- src/core/ffi.c
- src/core/inttypes.c
- src/core/math.c
- src/core/string.c
- test/suite-inttypes.janet
I noticed the typo in `*task-id*` so I ran spellcheck over the docstrings and found a couple more. Nothing too exciting here.
> fix some typos in docstrings

- src/core/buffer.c
Use libc strlen in janet_buffer_push_cstring
Platform libc's often contains optimized assembly implementations of strlen, so take
advantage of them here instead of doing a naive count.
> Use libc strlen in janet_buffer_push_cstring

- src/core/ev.c
- src/core/net.c
Not sure if this makes proper sense, needs some review.
This cleans up the unused `NetStateConnect` state in the connect state machine, but not allocating any state to pass to `janet_async_start()` hung my janet at cleanup time; I believe the refcount dec should not depend on state of `evdata`
> net/ev: Cleaned up unused NetStateConnect, fixed janet_async_end() ev refcount

- src/core/peg.c
- src/include/janet.h
- test/suite-peg.janet
~~The first commit in this branch condenses the two of the existing opcodes into a single opcode, so that there are still exactly 32 PEG opcodes. [I asked about this on Zulip](https://janet.zulipchat.com/#narrow/stream/399615-general/topic/implementation), and as I said there I'm still not very confident that this code is necessary. It does remove a conditional branch on the main bytecode loop, but I worry there might be some 32-bitness thing that I don't understand that might make it even more costly to remove.~~
It then proposes ~~two~~ one new special~~s~~:
`(sub window patt)` executes the `window` pattern, remembers how many bytes it matches, then executes `patt` over exactly the bytes matched by the `window`. This allows you to limit what the sub`patt`ern can match, e.g. `(sub (to …
> Add a new (sub) PEG special

- src/core/peg.c
- src/include/janet.h
- test/suite-peg.janet
This works similarly to `string/split`, but the separator is a PEG.
I also added a `peg/split` helper function, and a new opcode to optimize the `(to -1)` pattern so that it will only do two passes over the input instead of three.
> add a new (split) PEG special

- src/core/buffer.c
- test/suite-buffer.janet
I suspect many binary protocols need to encode/decode floats to/from big/little endian. Here is a first draft, should it be included in the standard library.
I am not tied to the `binary` module as I'm aware there exists `buffer/*` functions that are similar and it could possibly be bundled into the existing `buffer` module. I was concerned about the naming because `buffer/push-word` already exists and the signature is different with no control over endianness. I thought it might be confusing to add `buffer/push-uint32` in that case - but maybe not.
Additionally, `binary/write-float32` and `binary/write-float64` could potentially be removed if we implement something like `math/float32-bits` and `math/float64-bits` respectively for constructing sized `uint`s from the underlying bits and …
> Add buffer/push-* sized int and float

- src/core/os.c
As discused over gitter, `WIFSIGNALED` macro must be checked before one uses the `WTERMSIG` macro. This change reflects that necessity and adds a final else clause which will panic if no status code could be determined.
Also relevant is information gathered by @sogaiu in [question-about-WTERMSIG-in-janet.md](https://gist.github.com/sogaiu/92149bc1c085e4b7da40f650a4965b6a).
The idea here (currently, though it could be changed) is to panic when an unknown status code is encountered, as well as comply to the `man 2 waitpid` documentation.
> Fix: make `proc_get_status` compliant to OS documentation.

- src/core/os.c
It closes https://github.com/janet-lang/janet/issues/1386
> Improve documentation on subprocess API

- src/core/peg.c
It looks like this piece of text was overseen while renaming `repl` to `subst` in commit 485099fd6e9e88fdc7521fff7e54a6d7023e9871.
> Fix documentation of peg/replace

- examples/ffi/test.janet
- src/boot/boot.janet
I would like the ability to alias an FFI method in order to maintain the naming convention of the underlying shared library
As an example I would like to be able to do the following
```
(ffi/defbind-alias tb_poll_event _tb_poll_event :int [event :ptr])
(defn tb_poll_event
[]
(def event (ffi/write tb_event (tb_event/new)))
(_tb_poll_event event)
(zipcoll tb_event_keys (ffi/read tb_event event)))
```
The shared library method is called tb_poll_event but it requires a janet "wrapper" because it returns a struct pointer.
> Add ffi/defbind-alias

- src/include/janet.h
Tests all passed on my loongarch64 pc. You can also test on [gcc farm].(https://portal.cfarm.net/machines/list/)
```
$ meson test --print-errorlogs --no-rebuild -C output
1/28 test/suite-array.janet            OK              0.02s
2/28 test/suite-asm.janet              OK              0.01s
3/28 test/suite-capi.janet             OK              0.02s
4/28 test/suite-cfuns.janet            OK              0.01s
5/28 test/suite-buffer.janet           OK              0.02s
6/28 test/suite-compile.janet          OK              0.02s
7/28 test/suite-debug.janet            OK              0.02s
8/28 test/suite-corelib.janet          OK              0.02s
9/28 test/suite-ffi.janet              OK              0.02s
10/28 test/suite-io.janet               OK              0.02s
11/28 …
```
> Add LoongArch64 support

- src/core/buffer.c
- src/core/capi.c
- src/include/janet.h
- test/suite-buffer.janet
I was using the newer `buffer/push-uint[16|32|64]` functions and ran up against issues with upper limits.
```
error: bad slot #2, expected 32 bit signed integer, got 3927367768
in buffer/push-uint32 [src/core/buffer.c] on line 388
```
This fixes the issue. I think it is fair that negative numbers here raise bad slot errors so I modified those tests to test the upper bounds instead.
Well, `buffer/push-uint16` anything `0xFFFF <= x <= 0xFFFFFFF` will push `"\xff\xff"` without error until it exceeds `uint32_t`. We could add a similar `janet_getuinteger16`, `janet_checkuint16` , and `janet_checkuint16range` if that's an issue. Might look better to rename the 32-bit functions for consistency as well in that case so I thought I'd get feedback first if this is enough or what path we should take.
> Fix buffer push uint max

- examples/ffi/so.c
- examples/ffi/test.janet
- src/core/ffi.c
- test/suite-ffi.janet
This change adds support for the AAPCS64 calling convention, targeting Linux and macOS AARCH64 systems.
This was developed on a macOS target, which has "looser", Apple specific, alignment requirements than the base standard used by Linux.
Support for the latter has only been tested against a QEMU VM running Arch Linux ARM, so tests against actual hardware would be appreciated.
In general my use-case is pretty simple, so there might be bugs with more complex function signatures. I've added two tests for stack spilling and alignment differences to at least catch rudimentary errors here, but again, tests against more complex libraries would be appreciated.
Reading over the Windows [Overview of ARM64 ABI conventions](https://learn.microsoft.com/en-us/cpp/build/arm64-windows-abi-conventions) …
> Add support for the AAPCS64 calling convention

- src/mainclient/shell.c
Hi! Made a small patch for a recurring annoyance I had with the REPL. Only tested on Linux w/ WezTerm & Konsole but should work on any modern terminal
Thank you for making/maintaining such a nice programming language :)
---
Commit Description:
>Ctrl + left/right arrow would simply input "5D"/"5C" into the REPL which was useless and confusing
>
>With this change, it instead goes to the previous/next word which is usually expected in readline-like interfaces
> Add ctrl + left/right arrow support to the REPL

- src/boot/boot.janet
Changes behavior of `-c` flag such that:
* `janet -c foo.janet` writes to `foo.jimage`
* `janet -c foo` writes to `foo.jimage`
Previously these would cause a confusing error due to out of bounds access to the args array (see #1451).
The default is only used if there are no more arguments after the input file – I didn't add any special handling for edge cases like `janet -c foo.janet -h` (which uses '-h' as the output file).
closes #1451
> Add default output path for --compile (-c)

- src/boot/boot.janet
This PR partially reverts a change to `(compare)` that changed the fallback behaviour.
In #1249, @primo-ppcg sped up the `(compare)` function in Janet by using a macro. However, the macro wasn't a direct translation of the previous code. The code effectively went from this:
```janet
(or
(when-let [f (get x :compare)] (f x y))
(when-let [f (get y :compare)] (- (f y x)))
(cmp x y))
```
to this:
```janet
(if (def f (get x :compare))
(f x y)
(if (def f (get y :compare))
(- (f y x))
(cmp x y)))
```
In the original code, the use of `or` meant that the code would 'fall back' to the comparison function of the second operand if the comparison function of the first operand returns `nil` (with a further fallback to `(cmp)` if the second comparison function also returned `nil`). Now, as long as there …
> Fix fallback support in polymorphic compare

- CHANGELOG.md
There were two changes that were identified as being in the wrong place in the changelog in #1491. This fixes the other one.
> Move other unreleased change out of v1.35.2 section

- src/core/parse.c
`s->line` and `s->column` in `delim_error` are `size_t`, which is typically 64-bit, but `va_arg` in `janet_formatbv` reads `int32_t` for `%d`.
> Cast arguments to `int32_t` before passing to `janet_formatb` with `%d` format specifier

- .github/workflows/test.yml
Beginning with ad77bc391cb59e11deb116acd04eac04272839dd, the following error began occurring in GitHub's test runner when testing with the s390x/ubuntu Docker image:
```
docker: no matching manifest for linux/amd64 in the manifest list entries.
```
This may be because s390x/ubuntu images have become an image index and so require a platform specification (see https://github.com/nodejs/docker-node/issues/2110#issuecomment-2187459985).
This PR adds the `--platform` flag to the relevant Docker command in the GitHub workflow file to fix this problem.
> Update Docker command to use `--platform` flag

- src/core/string.c
Check string length before pointer equality, so that a string is not considered equal to a prefix slice of itself.
I ran into this with a pretty gnarly bug where e.g. `(symbol/slice 'abcdefg 0 3)` returned `'abcdefg` when the symcache was filled *just so* -- they hash differently, but if you get unlucky enough and there's a hash collision, the resolution runs `janet_string_equalconst` and erroneously says "oh yeah we found it" because `cfun_symbol_slice` just changes the `len`.
> fix janet_string_equalconst

- src/core/net.c
This PR modifies `net/read`'s docstring as part of addressing #1523.
For background, please see [this comment](https://github.com/janet-lang/janet/issues/1523#issuecomment-2510429337).
> Additional tweak to address #1523

- src/core/io.c
Adds fstat directory test after fopen, which can return non-NULL when passed a directory name on Linux.
Tested on Ubuntu 22.04 (+valgrind), & Windows 10
Should close #1530
> file/open: check if directory

- CHANGELOG.md
- src/core/ev.c
- test/suite-ev.janet
This PR adds `ev/to-file` as a way to allow synchronous operations with stream-based resources (e.g. sockets).
Janet supports non-blocking IO operations via the `ev` module. While this is desirable in many cases, there are situations where a user wants to ensure that an operation is synchronous. Janet does not currently offer a mechanism to do this with stream-based resources (e.g. sockets).
As discussed in #1531, one way to address this is is to offer a function that would create a `core/file` object based on the `core/stream` object. The `core/file` object could then be used with the synchronous operations in the `file` module.
The `src/core/ev.c` file is modified to add  an `ev/to-file` function. The function takes a stream object and attempts to return a file object. This can then be …
> Add `ev/to-file` for synchronous resource operations

- src/core/parse.c
- test/suite-parse.janet
This PR fixes the dedenting behaviour of long-strings that use Windows EOLs (i.e. `\r\n`). It fixes #1502.
Janet supports dedenting long-strings (i.e. strings delimited by one or more `` ` `` characters). This is particularly useful for docstrings where the docstring will usually be indented to preserve visual hierarchy.
As reported by @CFiggers in #1502, this practice ‘breaks’ with files that use `\r\n` as the EOL sequence. This is because Janet’s dedenting algorithm assumes the EOL sequence will be `\n`:
https://github.com/janet-lang/janet/blob/4daecc9a4113aa0198ddf30c90e59cc256a748d1/src/core/parse.c#L361-L407
By default, Git will use `\r\n` when cloning repositories on Windows even if the files in the repository used only `\n`. Git’s behaviour can be modified but requires affirmative …
> Support dedenting long-strings with Windows EOLs

- README.md
- build_win.bat
- tools/msi/janet.wxs
Small update to add Windows on Arm64 support. This does require changing the (os/arch) value from 'aarch64' to 'arm64' just for Windows on Arm.
Also requires the latest version 3.14 of the WiX toolset.
> Brief: Add Arm64 .msi support on Windows

- src/core/inttypes.c
All credits go to @sogaiu (see this [Zulip chat](https://janet.zulipchat.com/#narrow/channel/399615-general/topic/Advent.20of.20Code/near/493101919)).
The current doc strings for `int/u64` and `int/s64` say that these functions only support strings. But as far as I can tell from the [diff](https://github.com/janet-lang/janet/commit/bad040665fb742b1363b85e0c9f1736d43fc313c#diff-3a550951c59fd425cf0d44f6c0b3581d1e54135a7d07bb19d0e500548b99a8d1R68-R92) they always support both numbers and strings, and the test suites cover those cases. I therefore updated the docstrings to indicate that.
`int/to-number` used to only supports `int32` values but [this commit](https://github.com/janet-lang/janet/commit/75845c028364b8a25f06d620a61851cfa4505e64#diff-3a550951c59fd425cf0d44f6c0b3581d1e54135a7d07bb19d …
> Fix docstrings for int/u64, int/s64 and int/to-number

- .github/workflows/codeql.yml
The GitHub workflow that Janet runs to check code quality began failing with the merge of #1544 on 12 January 2025. This workflow uses version 2 of various CodeQL actions. According to [this blog post](https://github.blog/changelog/2025-01-10-code-scanning-codeql-action-v2-is-now-deprecated/ ), these actions were ‘retired’ on 10 January 2025.
This PR changes the version from 2 to 3. This is the [latest version](https://github.com/github/codeql-action?tab=readme-ov-file#supported-versions-of-the-codeql-action) at the time of this PR.
> Update CodeQL actions to latest version

- src/core/peg.c
- src/include/janet.h
- test/suite-peg.janet
This is... maybe not a real pull request; this is an idea with an implementation and some tests. But it's an idea that adds a bit of complexity to the PEG engine and is maybe not worth it.
I often want to write a PEG somewhere in between `to` and `thru`, usually while parsing something like `key=value`: capture everything up to `=`, skip over the `=`, and then match everything after. This is a little clumsy right now:
```
(* '(to "=") "=" '(to -1))
```
Because you have to repeat the separator (and even though this doesn't actually matter in any case where I've done this, it's a little sad that you evaluate the separator PEG one more time than is necessary).
So `(til)` is a special that makes this easy to write. It captures like `(to)`, but advances like `(thru)`.
And this is... weird. …
> add (til) PEG special

- src/core/os.c
This PR simplifies, while aiming to preserve the clarity of, the docstrings for various subprocess-related functions in `os.c`. It also tidies up some unnecessary return statements and Windows-related compiler conditional directives (i.e. `#ifdef`) .
In #1394, @amano-kenji added detail to the docstrings of a number of functions relating to subprocesses. This improved the explanations of behaviour relating to subprocesses that had been discussed in #1386. In short, it wasn't always clear how to avoid zombie processes and deadlock when using subprocesses. The docstrings were expanded to provide more detail on these points.
This PR attempts to simplify the wording of the docstrings by using consistent terminology. Small grammatical errors that may have impacted readability are also fixed.
> Improve subprocess-related docstrings and functions

- src/core/util.h
This PR addresses https://github.com/janet-lang/janet/issues/1571 by making the `janet_lib_ffi()` prototype declaration independent of `JANET_EV` being defined. 
This ensures that Janet can be compiled with a configuration which defines `JANET_NO_EV` but not `JANET_NO_FFI`.
> Remove janet_lib_ffi() dependency on JANET_EV

- src/core/ev.c
- src/core/state.h
- test/suite-ev.janet
This PR carries on from #1566. The background, implementation and limitations are largely the same as set out in that PR.
The key difference is that the background thread is now sent to sleep for the amount of the timeout (previously, the thread used `sleep(0)`). To avoid a scenario where the fiber being monitored has finished running but the background thread remains asleep (which would prevent the process from terminating), the thread is now cancelled. This is achieved on POSIX by using `nanosleep` (which creates a ['cancellation point'](https://www.man7.org/linux/man-pages/man3/pthread_cancel.3.html) for `pthread_cancel`) and on Windows by using `SleepEx` (which permits an [asynchronous procedure call](https://learn.microsoft.com/en-us/windows/win32/sync/asynchronous-procedure-calls) …
> Expand scope of code that works with `ev/deadline` again

- src/boot/boot.janet
This is an attempt to finish up #1574.
Docstrings for `mapcat`, `count`, `keep`, `all`, and `some` were adjusted along the lines of the modified docstring for `map` in https://github.com/janet-lang/janet/commit/363e32d4557c939c8dbcb069a0a7578b5b594daf.
> Tweak doc for mapcat, count, keep, all, some

- CHANGELOG.md
- src/core/ev.c
- src/include/janet.h
This PR fixes a build error on Android because `pthread_cancel` is [not implemented](https://android.googlesource.com/platform/bionic/+/refs/heads/main/docs/status.md#posix) in Bionic, the library Google uses for Android that implements parts of C like `pthread` (thanks to @sogaiu for bringing this to my attention). This PR uses signals for Android as a workaround.
> Fix absence of pthread_cancel in Android

- src/core/ev.c
I found out about this when reviewing some old code. I think it's merely a `/`  -> `*` typo.
> Try to fix cfun registry size check for cross-thread messages

- src/core/pp.c
Buffers are not always null-terminated, so using `strlen` here could cause reads past the end of the buffer and cause Janet to incorrectly report that the string contains zeros because the lengths don't match.
There may be other instances to fix, but this fixes #1600.
> Use strnlen when checking for null byte

- src/boot/boot.janet
Fixes #1603 
Also makes `(try 1 ([] (error "hi")))` valid.
> Patch try to accept (try body ([] catch-body))

- CHANGELOG.md
- src/boot/boot.janet
- test/suite-boot.janet
This confused me a lot, because I kept calling `(import ./mymodule :fresh)` and it wouldn't reload anything.
> Clarify :fresh usage in import

- src/boot/boot.janet
Since it is invalid to call accept on a datagram socket, net/server always errors if handler is truthy and type is :datagram.
Tweak the implementation to give a better error message in this case.
References: https://github.com/janet-lang/janet/issues/1614
> net/server: improve error for truthy handler and type :datagram

- Makefile
- README.md
- src/core/os.c
- src/include/janet.h
This change makes Janet build cleanly on illumos. (Specifically, OmniOS: I have not tried it on other distributions.)
- Fixes build problems.
- Makes `(os/cpu-count)` work.
- Makes all tests pass.
- Makes `(os/which)` return `:illumos`.
- Patches the `Makefile` to not call `strip` with `-S` on illumos
I used gcc-14.2.0 on OmniOS-r151054.
I have successfully used this port for some time now. I am able to use JPM, Spork etc, and build native binaries successfully.
If this patch is accepted, I will be happy to provide illumos patches for JPM and Spork.
<details>
<summary>expand</summary>
```
$ gmake install
gcc -DJANET_BOOTSTRAP -DJANET_BUILD="\"deede6ba\"" -O0 -std=c99 -Wall -Wextra -Isrc/include -Isrc/conf -fvisibility=hidden -fPIC -g -D__EXTENSIONS__ -DJANET_NO_NANBOX -o …
```
> illumos support

- src/core/ev.c
- src/core/state.h
This PR fixes a problem I introduced via #1575, namely that when built on Windows platforms Janet can hang when `ev/deadline` is called with a function that infinitely loops. The fix is to use `SetEvent` rather than `QueueUserAPC` with an increasing back-off if a timer completes in less time than the user had specified. 
The Windows implementation of `ev/deadline` uses a combination of `QueueUserAPC` and `SleepEx` to allow a worker thread to interrupt the main thread running the Janet VM if a timeout occurs. While the implementations used on POSIX systems seem to work reliably, CI runs of the Janet project on Windows have, over the past six months, repeatedly hung during the testing of `test/suite-ev.janet`.
I am now relatively confident that the problem is a consequence of the resolution …
> Use `SetEvent` rather than `QueueUserAPC` on Windows
