- examples/utils.dst
I added  reverse and comp functions, as well as if-let macro experimentally. If you think it is appropriate, you can move them to boot.dst.
I will also implement let as monads (as it is originally is). Tell me your opinion.
I like the iter approach you  implemented there :)
> :sparkles: Add examples

- examples/utils.dst
Here is when-not/let and if-not :P .
> Add more clojure functions in the examples

- examples/lazyseqs.dst
I notice that   (type :=) => symbol. That implies that type doesn't return the type 
binded to that symbol (cfunction maybe?).  How does binding to symbols work? Seems that := are
special symbols that are parsed differently from the other symbols ? I like the symbol only approach by the way.
My implementation of iter2lazyseq causes a segmentation fault, not sure why. Try it with the function filter2
Do you know  if lazyseq would be more efficient if it memoized more elements? I know that the clojure 
lazy-seq always realizes 32.
Also i am curious, have you in mind something similar to deftype/defprotocol ? Or maybe you have something other in mind more suitable for a lua/clojure (seems to me like that) hybrid?
> Some issues

- examples/lazyseqs.dst
- src/compiler/boot.dst
- src/compiler/specials.c
Hi, here are some thoughts
I've been reading about metatables and i find them an interesting concept. Can the mechanism be used to 
create a more "formal" type/object ? Your thoughts on metatables make sense since there is no host language
I am curious, what is the motivation of using :keywords ? Since there is no IFn protocol, wouldn't 
a quote suffice ? like 'symbol. Or ''symbol if you want macros. Nobody uses them that way but 'symbol in clojure maps behave like :keyword (and also implement IFn protocol).
Sorry for bothering you with questions, thank you in advance.
And something else i have in mind. It might be difficult if someone read the code to distinguish between mutable from immutable data types. The same thing happens in clojure a lot with atoms, but  a naming convention is …
> Some thoughts 

- src/core/math.c
Added missing math/abs binding
> Added math/abs binding

- Makefile
Quick PR to add OpenBSD support the build out of the box.
> Update makefile for OpenBSD

- examples/tarray.janet
- src/core/abstract.c
- src/core/corelib.c
- src/core/io.c
- src/core/marsh.c
- src/core/parse.c
- src/core/peg.c
- src/core/typedarray.c
- src/core/util.c
- src/core/util.h
- src/include/janet.h
- test/suite5.janet
Fixes #51 
Feel free to modify the code according to your taste.
> Binary Typed Array  for Janet

- src/core/value.c
Fix a little bug in AbstractType get/set panic message.
> fix AbstractType get/set error message

- Makefile
This PR adds some recipes to the makefile to produce a static library archive via ar. I figured it would be a useful thing to have.
Let me know if there are any problems with it.
> Add static library

- src/core/capi.c
- src/include/janet.h
The api is still not used automatically by modules as that would be a breaking change.
> Add api for checking build compatibilty.

- src/boot/boot.janet
- test/suite5.janet
Cont #154 
Did something stupid to my fork branch.
> Take and drop

- .gitignore
- src/mainclient/line.c
Just a tiny case statement that I noticed was missing from the repl when I went to use the delete key.
> Add support for delete key in repl

- meson.build
This will create feature parity to the Makefile.
> Create janet.pc also from Meson.

- src/core/asm.c
> Check some *alloc return values

- test/fuzzers/fuzz_dostring.c
Hi,
I starting fuzzing Janet and have created an initial integration with OSS-Fuzz. The fuzzer is in the pull request and the integration with OSS-Fuzz will occur in their own repository (https://github.com/google/oss-fuzz). The build itself occurs within OSS-Fuzz and the code will be continuously fuzzed. If you are interested then please merge the request and provide me with an email to which bug reports will be sent - notice this email will be publicly visible. I am happy to continue creating fuzzers for the project if you would like but the current fuzzer covers a good amount of the code so this should be fairly useful in finding bugs.
David
> Added a fuzzer and integration with OSS-Fuzz.

- src/core/fiber.c
Added some flags (t, i, and p) that were not mentioned in an error message.
> Add flags to fiber/new error message

- README.md
I added a couple of instructions on how to build the .msi with given the (very appreciated) changes in #406
> adds WiX details to README

- src/boot/boot.janet
- src/core/inttypes.c
- test/suite0.janet
Addresses issue #272 by implementing compare, compare<,compare= (etc.) functions.  Implements compare method for int/s64 and int/u64.  Removes vestigial comparison methods on int/s64 and int/u64.
> Implement polymorphic compare

- test/suite8.janet
The file is also formatted by `fmt/format-file` from spork. Please let me know if it can stay like this, or that I should revert those changes.
> Add keyword/slice and symbol/slice tests

- test/suite8.janet
Please let me know if I should add some more involved tests.
> Add tests for peg/find and peg/find-all

- jpm.1
Fix some typos. I don't know groff, but these changes fix a few issues.
> fix jpm.1 typos

- examples/assembly.janet
As I am wandering around ev, I have found this example was not working in its old version, so I fixed it. I also reformat it with the spork/fmt.
> Fix asm example

- src/boot/boot.janet
Since those represent code, they should get backticks.
> boot.janet, compare*, light formatting

- src/boot/boot.janet
Arranged this way seems to make more sense.
> boot.janet, cond doc

- src/boot/boot.janet
> boot.janet, fix possible typo

- src/core/corelib.c
> light markup in some docs in corelib

- src/boot/boot.janet
> Remove redundant do

- src/boot/boot.janet
- test/suite0001.janet
The value is nil to be consistent for and/or and all/some.
Also add some tests for and/or.
> Fix or with zero arguments

- meson.build
Found out how to fix it...
Closes #661.
> Fix include path when using meson

- src/core/ev.c
- src/core/os.c
- test/suite0009.janet
Fixes https://github.com/janet-lang/janet/issues/716.
> Fix os open write windows, and add TerminateProcess calls

- src/boot/boot.janet
Pass in indexed and bytes, return tuples and strings, respectively.
> Clarify docs on take and drop functions

- src/core/ev.c
- src/include/janet.h
> Update ev.c to use the new binding style that provides source information

- src/core/math.c
- src/core/util.h
- src/include/janet.h
> Update math.c for the new style

- src/mainclient/shell.c
This fixes #917. In mainclient, all errors in `read` were assumed to be due to EOF or other unhandleable error, which is not true for EINTR in which case the call should simply be retried.
This doesn't fix every instance of I/O where EINTR could appear, only the ones that are most likely to encounter it due to blocking for potentially long amounts of time due to user input. Nevertheless, if this were to be done properly, all `read`, `write` and `ioctl` (and possibly other?) operations within mainclient should be EINTR-retried too.
Another caveat is that I'm not sure that the `simpleline` portion is suitable for MSVC. From what I can tell, `errno` [does exist](https://docs.microsoft.com/en-us/cpp/c-runtime-library/errno-doserrno-sys-errlist-and-sys-nerr?view=msvc-170) there, but I'm not …
> Handle interrupts during `read` properly in mainclient

- src/core/ev.c
Previous implementation would fail to prune silly timeouts such as `(ev/with-deadline 30 nil)`, causing the event loop for wait for 30 seconds even though the deadline-ridden fiber has long since finished. This borrows the logic from timeout dispatch which, for the time being, works fine.
> ev: Fix timeout pruning logic

- src/core/corelib.c
> Update docs for `describe`

- src/core/array.c
Added some backticks around code in docstrings to distinguish from prose.
> array.c docstrings

- src/core/buffer.c
Added backticks around code in docstrings to distinguish from prose.
> buffer.c docstrings

- src/core/parse.c
Added some backticks around code in docstrings to distinguish them from prose. Plus 2 minor edits for clarity.
> parse.c docstrings

- src/core/os.c
Some code backticks in docstrings where useful. Also some light editing (punctuation, caps, etc.).
> os.c docstrings

- src/core/io.c
> io.c docstrings

- src/boot/boot.janet
> boot.janet docstrings

- src/boot/boot.janet
> boot.janet docstrings (part 2)

- src/boot/boot.janet
> boot.janet docstrings (part 3, last part)

- src/core/peg.c
- test/suite0014.janet
> Made peg 'not' and 'if-not' drop their captures on success

- src/boot/boot.janet
- src/core/ev.c
> Fix documentation for ev/go, ev/spawn

- src/core/io.c
https://github.com/janet-lang/janet/issues/1062
> use int32_t type for file flags, just like header

- .github/workflows/test.yml
- src/core/features.h
Not sure if this adds anything to the current CI, also the job is a tad more heavy than the others because it needs to install wine and mingw cross compilers first.
Feel free to not apply :)
> Add CI test for mingw/wine on linux

- src/core/buffer.c
> Updated documentation for buffer/push-at

- src/boot/boot.janet
- src/core/os.c
> added os/isatty, do not enable colors if stdout is not a tty

- src/boot/boot.janet
- Speeds up `interleave`
- Speeds up `interpose`
- Updates `interpose` to work with non-lengthable types
- Removes one level of unrolling in `map-template`
```janet
(def a (range 1000))
(timeit-loop [:timeout 1] "interpose " (interpose 0 a))
(timeit-loop [:timeout 1] "interleave" (interleave "abcd" "1234" "wxyz"))
(print ;(interpose " " (generate [i :range [10]] i)))
```
master:
```janet
interpose  1.000s, 24.43µs/body
interleave 1.000s, 0.8582µs/body
error: expected string, symbol, keyword, array, tuple, table, struct or buffer, got <fiber 0x56056E4D9220>
in interpose [boot.janet] on line 1723, column 12
```
branch:
```janet
interpose  1.000s, 16.86µs/body
interleave 1.000s, 0.5421µs/body
0 1 2 3 4 5 6 7 8 9
```
---
`interleave` has become synonymous with `mapcat tuple`, …
> Update `interleave`, `interpose`

- src/mainclient/shell.c
> Change Alt-f in the REPL move to next end of word instead of beginning

- src/core/corelib.c
> fix (doc next)

- src/core/net.c
This PR add a new core function, `net/socket`, to create an unbound network socket. 
I believe this is useful for handling flexible port assignments, as seen in protocols like TFTP.
And the following are Janet server/client codes that implement the server/client examples attached to issue #1622, using the `net/socket` API added in this PR.
Server:
```
(def listen-sock (net/listen "127.0.0.1" 8080 :datagram))
(print "Server listening on 127.0.0.1:8080")
(def buff (buffer/new 1024))
(def recv-info (net/recv-from listen-sock 1024 buff))
(print "Server received: " buff " from port " ((net/address-unpack recv-info) 1))
(def world-msg "world")
(def new-sock (net/socket :datagram))
(net/send-to new-sock recv-info world-msg)
(print "Server sent: " world-msg)
(net/close listen-sock)
(net/close …
```
> Add `net/socket` for unbound socket creation for #1622
